class TFEngine{
  constructor(change){this.change=change;this.running=false;this.abort=null;this.interrupted=null;this.tabId=null;}
  check(){if(this.abort?.signal.aborted)throw Object.assign(Error(this.interrupted==='stopped'?'Dihentikan paksa.':'Scan dijeda.'),{interrupted:this.interrupted});}
  async guarded(promise){this.check();const signal=this.abort?.signal;if(!signal)return promise;let handler;const cancelled=new Promise((_,reject)=>{handler=()=>reject(Object.assign(Error(this.interrupted==='stopped'?'Dihentikan paksa.':'Scan dijeda.'),{interrupted:this.interrupted}));signal.addEventListener('abort',handler,{once:true});});try{return await Promise.race([promise,cancelled]);}finally{signal.removeEventListener('abort',handler);}}
  async save(){this.job.heartbeatAt=Date.now();await chrome.storage.local.set({tfMultiJobV419:this.job});this.change(this.job);}
  async phase(name,index,fraction,message,inside){this.check();inside=inside??(fraction===0?false:this.job.progress?.inside||false);this.job.progress={name,index,fraction,message,inside};await this.save();}
  async log(message){this.job.logs.push(new Date().toLocaleTimeString('id-ID')+' '+message);this.job.logs=this.job.logs.slice(-300);await this.save();}
  async interrupt(status,control){if(!this.running)return;if(control){this.job.lastControl={action:control.action,source:control.source||'unknown',at:new Date(control.at||Date.now()).toISOString()};this.job.logs.push(new Date().toLocaleTimeString('id-ID')+' Kontrol '+control.action.toUpperCase()+' · sumber: '+(control.source||'unknown'));}this.interrupted=status;this.abort.abort();const id=this.tabId;this.tabId=null;if(Number.isInteger(id)){try{await chrome.tabs.remove(id);}catch{}}}
  async openScanTab(url){
    this.check();const previous=this.tabId;this.tabId=null;if(Number.isInteger(previous)){try{await this.guarded(chrome.tabs.remove(previous));}catch{this.check();}}
    const windowId=(await chrome.tabs.getCurrent()).windowId;const controller=this.abort;const tab=await this.guarded(chrome.tabs.create({url,active:false,windowId}).then(async tab=>{if(controller.signal.aborted){await chrome.tabs.remove(tab.id);throw Error('Navigasi dibatalkan.');}return tab;}));this.tabId=tab.id;await chrome.storage.local.set({tfMultiOwnedTabV419:tab.id});
  }
  async navigate(url){
    await this.openScanTab(url);
    for(let attempt=1;attempt<=2;attempt++){
      const deadline=Date.now()+60000;while(Date.now()<deadline){
        this.check();const tab=await this.guarded(chrome.tabs.get(this.tabId));
        if(tab.status==='complete'&&tab.url&&!tab.url.startsWith('https://account.tradersfamily.id/channels/'))throw Error('Login TF diperlukan.');
        try{
          const packet=await this.guarded(chrome.scripting.executeScript({target:{tabId:this.tabId},injectImmediately:true,func:(expected)=>{
            const target=new URL(expected);if(location.origin!==target.origin||location.pathname!==target.pathname)return false;
            if(document.readyState==='loading')return false;
            return target.pathname==='/channels/browse/'?!!document.querySelector('#channel-content-container')&&!!document.querySelector('#dataSummaryChannel'):!!document.querySelector('a[href="#tab_summary"]')&&!!document.querySelector('#global-filter');
          },args:[url]}));
          if(packet?.[0]?.result===true){if(tab.status!=='complete')await this.log('Isi halaman TF siap; melanjutkan tanpa menunggu resource tambahan.');return;}
        }catch(error){this.check();if(tab.status==='complete'&&/Cannot access|permission|Missing host/i.test(error.message))throw error;}
        await this.guarded(new Promise(r=>setTimeout(r,500)));
      }
      if(attempt===1){await this.log('Navigasi TF terlambat · mencoba ulang 1/1; hasil scan dipertahankan.');await this.openScanTab(url);}
    }
    throw Error('Halaman TF belum siap setelah 2 percobaan. Periksa koneksi atau login, lalu klik Resume.');
  }
  async dom(stage,arg){
    let reason='respons DOM kosong';for(let attempt=1;attempt<=3;attempt++){this.check();await this.guarded(chrome.scripting.executeScript({target:{tabId:this.tabId},injectImmediately:true,files:['multi-scanner/collector.js']}));const result=await this.guarded(chrome.scripting.executeScript({target:{tabId:this.tabId},injectImmediately:true,func:async(stage,arg)=>{try{if(typeof globalThis.tfScanDOM!=='function')throw Error('Collector belum tersedia.');return {ok:true,data:await globalThis.tfScanDOM(stage,arg)};}catch(error){return {ok:false,error:String(error?.message||error)};}},args:[stage,arg||{}]}));this.check();const packet=result?.[0]?.result;
      if(packet?.ok===false){reason=packet.error||'pembacaan DOM gagal';if(stage==='historyStart'&&/Jumlah signal terlalu sedikit/i.test(reason))return {unavailable:true,pair:arg?.pair,reason};if(!/belum selesai|belum tersedia|History Signal tidak lengkap|Tanggal Closed at tidak terbaca/i.test(reason))throw Error(stage+': '+reason);}
      else if(packet?.ok===true&&packet.data&&typeof packet.data==='object'){const data=packet.data;let valid=stage==='portfolio'?Number.isInteger(data.months)&&data.months>0:stage==='summary'?typeof data.summary==='string':stage==='score'?typeof data.score==='string':stage==='profile'?typeof data.summary==='string'&&typeof data.score==='string':stage==='historyStart'&&data.unavailable===true||Array.isArray(data.rows)&&(stage.endsWith('More')?typeof data.done==='boolean':true);if(valid&&stage==='profile'){try{TFCore.summary(data.summary);TFCore.score(data.score);}catch(error){valid=false;reason=error.message;}}if(valid)return data;reason=reason==='respons DOM kosong'?'struktur hasil DOM tidak lengkap':reason;}
      else reason='halaman belum mengembalikan data DOM';
      if(attempt<3){await this.log(stage+': '+reason+' · mencoba lagi '+attempt+'/3');await this.guarded(new Promise(resolve=>setTimeout(resolve,1500)));if(stage==='profile'||stage==='inventoryStart'){const current=await this.guarded(chrome.tabs.get(this.tabId));if(current.url?.startsWith('https://account.tradersfamily.id/channels/')){await this.log('Memuat ulang halaman TF untuk memulihkan panel yang belum lengkap.');await this.navigate(current.url);}}}
    }throw Error(stage+': '+reason+' setelah 3 percobaan. Klik Resume untuk mengulang card ini.');
  }
  async start(filters){return navigator.locks.request('tf-multi-runner-v419',{ifAvailable:true},async lock=>{if(!lock)throw Error('Runner aktif di dashboard lain.');const state=await chrome.storage.local.get(['tfMultiJobV419','tfScanInProgress']);if(state.tfScanInProgress)throw Error('Batch scan utama masih berjalan.');if(state.tfMultiJobV419&&['running','paused','error'].includes(state.tfMultiJobV419.status))throw Error('Gunakan Resume atau Stop untuk scan sebelumnya.');TFCore.validate(filters);if(state.tfMultiJobV419)await chrome.storage.local.set({['tfMultiArchiveV419-'+state.tfMultiJobV419.id]:state.tfMultiJobV419});await chrome.storage.local.remove('tfMultiCommandV419');const end=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});this.job={id:crypto.randomUUID(),status:'running',filters:structuredClone(filters),asOf:end,ranges:TFCore.ranges(end,filters.historyMonths),inventory:[],inventoryComplete:false,cursor:0,results:[],skipped:[],evidence:[],logs:[],createdAt:new Date().toISOString()};return this.runLocked();});}
  async resume(job){return navigator.locks.request('tf-multi-runner-v419',{ifAvailable:true},async lock=>{if(!lock)throw Error('Runner aktif di dashboard lain.');const state=await chrome.storage.local.get(['tfMultiJobV419','tfScanInProgress']);if(state.tfScanInProgress)throw Error('Batch scan utama masih berjalan.');this.job=state.tfMultiJobV419||job;if(!this.job||this.job.status==='complete'||this.job.cursor>=this.job.inventory.length&&this.job.inventoryComplete)return;await chrome.storage.local.remove('tfMultiCommandV419');await this.log('Resume eksplisit: lanjut dari card '+(this.job.cursor+1)+'; hasil sebelumnya dipertahankan.');return this.runLocked();});}
  async runLocked(){this.running=true;this.abort=new AbortController();this.interrupted=null;this.job.status='running';delete this.job.error;const heartbeat=setInterval(()=>{if(this.running&&!this.abort.signal.aborted)chrome.storage.local.set({tfMultiHeartbeatV419:Date.now()});},3000);await chrome.storage.local.set({tfMultiHeartbeatV419:Date.now()});await this.save();try{
    const f=this.job.filters={...TFCore.defaults,...this.job.filters};
    if(!this.job.inventoryComplete){await this.log('Memuat seluruh card sesuai filter…');await this.navigate('https://account.tradersfamily.id/channels/browse/?');let batch=await this.dom('inventoryStart',f);this.check();this.job.inventory=batch.rows;await this.save();while(true){batch=await this.dom('inventoryMore');this.check();this.job.inventory=batch.rows;await this.save();if(batch.done){this.job.inventoryComplete=true;this.job.inventoryEnd=batch.endEvidence;await this.save();break;}}await this.log(this.job.inventory.length+' card ditemukan.');}
    while(this.job.cursor<this.job.inventory.length){this.check();const card=this.job.inventory[this.job.cursor],index=this.job.cursor+1;await this.phase(card.name,index,0,'Memeriksa Level dan Losing Month');
      if(!TFCore.cardAllowed(card,f)){this.check();this.job.skipped.push({id:card.id,name:card.name,reason:'Level / Losing Month tidak sesuai'});this.job.cursor++;await this.phase(card.name,index,1,'Skip: Level / Losing Month');continue;}
      await this.phase(card.name,index,.05,'Membuka card analis');await this.navigate(card.url);await this.phase(card.name,index,.08,'Memeriksa umur portofolio',true);
      let rejection=null;const evidence={card,windows:[]};const portfolio=(f.minimumPortfolioOn||f.requireFixed)?await this.dom('portfolio'):null;evidence.portfolio=portfolio;
      if(f.minimumPortfolioOn&&portfolio.months<f.minimumPortfolioMonths)rejection='Minimum Portofolio '+portfolio.months+' < '+f.minimumPortfolioMonths+' months';
      let consecutive=null,score={},matches=[];
      if(!rejection){await this.phase(card.name,index,.12,'Summary ALL');const profile=await this.dom('summary');evidence.profile=profile;consecutive=TFCore.summary(profile.summary);evidence.consecutive=consecutive;if(consecutive>f.maxConsecutive)rejection='Consecutive Loss '+consecutive;}
      if(!rejection&&(f.survivedOn||f.requireFixed)){await this.phase(card.name,index,.2,f.survivedOn?'Statistics · Survived Month':'Statistics · ketersediaan bulan History');const statistics=await this.dom('statistics');evidence.statistics=statistics;if(f.survivedOn)rejection=TFCore.survived(statistics.rows,f.survivedMonths);}
      if(!rejection&&TFCore.scoreFields.some(spec=>(f[spec.key]||[]).length)){await this.phase(card.name,index,.27,'Score · skor yang dipilih');const data=await this.dom('score');score={...TFCore.score(data.score),...TFCore.scoreDetails(data.score)};evidence.score=data;evidence.profile={...evidence.profile,...data};rejection=TFCore.accepted(score,f);}
      const status=score.status||card.status||(/Priority Channel/i.test(card.raw)?'Priority':/Prospect Channel/i.test(card.raw)?'Prospect':'Basic');
      if(!rejection&&f.statuses.length&&!f.statuses.includes(status))rejection='Status '+status+' tidak sesuai';
      if(!rejection&&f.requireFixed){const windows=TFCore.availableRanges(this.job.asOf,f.historyMonths,portfolio.months,evidence.statistics.oldest);evidence.effectiveRanges=windows;if(!windows.length)rejection='Tidak ada periode History yang tersedia';
        for(let w=0;!rejection&&w<windows.length;w++){const range=windows[w],fraction=.3+.6*w/windows.length;await this.phase(card.name,index,fraction,`History ${f.pair}: ${range.start} s/d ${range.end}`);let batch=await this.dom('historyStart',{...range,pair:f.pair});if(batch.unavailable){rejection=batch.reason?'History TF tidak tersedia: '+batch.reason:'Pair '+f.pair+' tidak tersedia';evidence.historyUnavailable={range,reason:rejection};break;}let rows=batch.rows;while(true){await this.phase(card.name,index,fraction,`History ${w+1}/${windows.length} · ${rows.length} signal dimuat`);batch=await this.dom('historyMore');rows=batch.rows;if(batch.done)break;}for(const row of rows){const date=TFCore.closedDate(row.closed_at_wib);if(/Pips/i.test(row.result)&&(!date||date<range.start||date>range.end))throw Error('Closed at di luar rentang.');if(row.symbol!==f.pair)throw Error('Pair history tidak sesuai.');}this.check();evidence.windows.push({range,rows,endEvidence:batch.endEvidence});this.job.currentEvidence=evidence;await this.phase(card.name,index,.3+.6*(w+1)/windows.length,`History ${w+1}/${windows.length} selesai`);}
        if(!rejection){await this.phase(card.name,index,.95,'Menghitung pips negatif yang sama persis');matches=TFCore.fixed(evidence.windows.flatMap(w=>w.rows),f.pair,f.fixedRepeatsOn===false?1:f.minRepeats,windows[0].start,this.job.asOf);evidence.fixedMatches=matches;if(!matches.length)rejection='Tidak ada pips negatif sama persis sebanyak '+(f.fixedRepeatsOn===false?1:f.minRepeats)+' kejadian';}}
      if(!rejection){this.check();this.job.results.push({name:card.name,url:card.url,pair:f.pair,sl:f.requireFixed&&f.fixedRepeatsOn!==false?matches[0].value:null,slFixedChecked:!!f.requireFixed&&f.fixedRepeatsOn!==false,repeat:f.requireFixed&&f.fixedRepeatsOn!==false?matches[0].count:null,consecutive,profitFactor:score.profitFactor??null,losing:`${card.losing}/${card.denominator}`,level:card.level,status,...score});}
      this.check();if(rejection)this.job.skipped.push({id:card.id,name:card.name,reason:rejection});this.job.evidence.push(evidence);delete this.job.currentEvidence;this.job.cursor++;await this.phase(card.name,index,1,rejection?'Skip: '+rejection:'Lolos · pemeriksaan selesai');await this.log(card.name+' · '+(rejection?'skip: '+rejection:'LOLOS'));}
    this.check();this.job.status='complete';this.job.finishedAt=new Date().toISOString();await this.log('Semua '+this.job.inventory.length+' card selesai dievaluasi.');
  }catch(e){this.job.status=this.interrupted||e.interrupted||'error';this.job.error=this.job.status==='stopped'?'Dihentikan paksa. Hasil analis selesai tetap tersimpan.':this.job.status==='paused'?'Dijeda. Resume mengulang card yang belum selesai.':e.message;await this.log(this.job.error);}finally{clearInterval(heartbeat);this.running=false;await chrome.storage.local.set({tfMultiHeartbeatV419:0});const id=this.tabId;this.tabId=null;if(Number.isInteger(id)){try{await chrome.tabs.remove(id);}catch{}}await chrome.storage.local.remove('tfMultiOwnedTabV419');await this.save();}}
}
globalThis.TFEngine=TFEngine;
