const $=s=>document.querySelector(s),D=TFCore.defaults;
const chip=(name,value,label)=>`<label class="chip"><input type="checkbox" name="${name}" value="${value}">${label||value}</label>`;
const number=(key,label,min='',max='')=>`<div class="field"><label for="${key}">${label}</label><input type="number" step="any" id="${key}" min="${min}" max="${max}"></div>`;
const range=(a,b,label,unit)=>`<label>${label} ${unit?`(${unit})`:''}</label><div class="range"><input aria-label="${label} minimum" type="number" step="any" id="${a}" placeholder="Min"><span>–</span><input aria-label="${label} maksimum" type="number" step="any" id="${b}" placeholder="Max"></div>`;
$('#filters').innerHTML=`<section><h2>Filter</h2><label>Level (maks. 2; kosong = semua)</label><div class="chips">${['Newbie','Rookie','Pro','Elite','Master','Legend'].map(v=>chip('levels',v)).join('')}</div><label>Status (maks. 2; kosong = semua)</label><div class="chips">${['Priority','Prospect','Basic'].map(v=>chip('statuses',v,(v==='Basic'?'':'✓ ')+v+' Channel')).join('')}</div>${range('scoreMin','scoreMax','Score','')}<label>Data Summary</label><select id="summary"><option value="12">1 tahun terakhir</option><option value="6">6 bulan terakhir</option></select><div class="field"></div><label>Sort by</label><select id="sort"><option value="subs">Subscriber</option><option value="total_profit">Total Profit</option><option value="medal">Medal</option><option value="amp">Avg. Monthly Profit</option><option value="probability">Probability</option><option value="post_per_month">Jumlah Post Bulanan</option><option value="score">Score</option></select></section><section><h2 class="section-title">Advanced</h2>${number('losingMax','Losing Month maksimal (filter TF)',0,12)}${range('probabilityMin','probabilityMax','Probability','%')}${range('tpMin','tpMax','Average TP','Pips')}${range('risk','reward','Risk : Reward','')}</section><section><h2 class="section-title">Profil Risiko</h2>${range('profitMin','profitMax','Avg. Monthly Profit','Pips')}${number('maxLoss','Max. Loss (%)',0,100)}</section><section><h2 class="section-title">Pemeriksaan card & analis</h2><label>Losing Month yang diterima</label><div class="chips">${Array.from({length:13},(_,i)=>chip('losingAllowed',i,String(i))).join('')}</div><p class="muted">Penyebut mengikuti Data Summary (12 atau 6 bulan).</p>${number('maxConsecutive','Consecutive Loss maksimal · Summary ALL',0)}<label>Recovery Factor · skor yang diterima</label><div class="chips">${[0,1,2,3,4].map(v=>chip('recoveryAllowed',v,v+'/4')).join('')}</div><label for="pair">Pair</label><input id="pair" list="pairs" placeholder="XAUUSD"><datalist id="pairs">${['XAUUSD','XAGUSD','EURUSD','GBPUSD','USDJPY','USDCHF','USDCAD','AUDUSD','NZDUSD','GBPJPY','EURJPY','AUDJPY','CADJPY','CHFJPY','NZDJPY','EURGBP','EURAUD','EURCAD','EURNZD','EURCHF','GBPAUD','GBPCAD','GBPCHF','GBPNZD','AUDCAD','AUDCHF','AUDNZD','CADCHF','NZDCAD','NZDCHF'].map(v=>`<option value="${v}">`).join('')}</datalist><p class="muted">Bisa mengetik pair lain. Setiap scan memeriksa satu pair.</p>${number('historyMonths','History Signal · bulan terakhir',1,60)}${number('minRepeats','Minimal kejadian pips negatif yang sama persis',1)}<p class="muted">SL fixed memakai hasil penutupan, misalnya −150.0 Pips. Nilai berbeda tidak dibulatkan menjadi sama.</p></section>`;
let currentJob=null;const hasChrome=typeof chrome!=='undefined'&&!!chrome.storage;
function fill(f){for(const [k,v]of Object.entries(f)){if(Array.isArray(v))document.querySelectorAll(`[name="${k}"]`).forEach(e=>e.checked=v.includes(['levels','statuses'].includes(k)?e.value:Number(e.value)));else if($('#'+k))$('#'+k).value=v;}limits();}
function limits(){['levels','statuses'].forEach(n=>TFMultiProgress.limit(document,n));}
function read(){const f={};for(const [k,v]of Object.entries(D)){if(Array.isArray(v))f[k]=Array.from(document.querySelectorAll(`[name="${k}"]:checked`),e=>['levels','statuses'].includes(k)?e.value:Number(e.value));else if(k==='requireFixed')f[k]=true;else{const e=$('#'+k);f[k]=typeof v==='number'?(e.value===''?'':Number(e.value)):e.value;}}f.pair=f.pair.trim().toUpperCase();return TFCore.validate(f);}
function syncControls(){if(parent!==window)parent.postMessage({type:'TF_MULTI_CONTROLS',buttons:['start','pause','dashboard','reset'].map(id=>({id,text:$('#'+id).textContent,disabled:$('#'+id).disabled,stop:$('#'+id).classList.contains('stop')}))},location.origin);}
function render(job){currentJob=job;TFMultiProgress.paint(job);const active=job&&['running','paused','error'].includes(job.status);$('#start').textContent=active?'Stop':'Submit';$('#start').classList.toggle('stop',!!active);$('#pause').textContent=job?.status==='running'?'Pause':'Resume';$('#pause').disabled=!job||!['running','paused','error'].includes(job.status);$('#reset').disabled=!!active;document.querySelectorAll('#filters input,#filters select').forEach(e=>e.disabled=!!active);if(!active)limits();const names={running:'Sedang berjalan',paused:'Dijeda',error:'Error',stopped:'Dihentikan',complete:'Selesai'};$('#message').textContent=job?`${names[job.status]} · ${job.results.length} lolos · ${job.skipped.length} skip${job.error?'\n'+job.error:''}`:'Semua card hasil filter dievaluasi tanpa batas jumlah analis.';syncControls();}
async function send(message){if(!hasChrome)throw Error('Pratinjau UI. Scan tersedia setelah extension dipasang.');const response=await chrome.runtime.sendMessage(message);if(!response?.ok)throw Error(response?.error||'Runner tidak merespons.');return response;}
function showError(e){$('#message').textContent=e.message;$('#message').classList.add('error');}
$('#filters').onchange=limits;$('#reset').onclick=()=>fill(D);$('#dashboard').onclick=()=>send({type:'TF_MULTI_OPEN'}).catch(showError);
$('#start').onclick=async()=>{try{if(currentJob&&['running','paused','error'].includes(currentJob.status)){await send({type:'TF_MULTI_CONTROL',action:'stop',jobId:currentJob.id});return;}const filters=read();await chrome.storage.local.set({tfMultiFiltersV419:filters});await send({type:'TF_MULTI_START'});}catch(e){showError(e);}};
$('#pause').onclick=()=>send({type:'TF_MULTI_CONTROL',action:currentJob?.status==='running'?'pause':'resume',jobId:currentJob?.id}).catch(showError);
fill(D);if(hasChrome){chrome.storage.local.get(['tfMultiFiltersV419','tfMultiJobV419']).then(s=>{fill(s.tfMultiFiltersV419||D);render(s.tfMultiJobV419);});chrome.storage.onChanged.addListener((c,a)=>{if(a==='local'&&c.tfMultiJobV419)render(c.tfMultiJobV419.newValue);});}
new ResizeObserver(()=>parent.postMessage({type:'TF_MULTI_HEIGHT',height:Math.ceil(document.documentElement.scrollHeight)},'*')).observe(document.body);

if(parent!==window){document.body.classList.add('embedded');window.addEventListener('message',event=>{if(event.source!==parent||event.origin!==location.origin||event.data?.type!=='TF_MULTI_ACTION'||!['start','pause','dashboard','reset'].includes(event.data.action))return;const button=$('#'+event.data.action);if(!button.disabled)button.click();});syncControls();}
