const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');const root=process.env.TF_REV419_ROOT||'outputs/TF_Extension_PC_MAC_REV419_MULTI_LINK',C=require(path.resolve(root,'multi-scanner/core.js'));
for(const dir of ['assets','multi-scanner'])for(const file of fs.readdirSync(root+'/'+dir).filter(n=>n.endsWith('.js')))new vm.Script(fs.readFileSync(root+'/'+dir+'/'+file,'utf8'),{filename:file});
const store={},removed=[],chrome={storage:{local:{set:async data=>Object.assign(store,structuredClone(data)),get:async keys=>Object.fromEntries((Array.isArray(keys)?keys:[keys]).map(k=>[k,structuredClone(store[k])])),remove:async keys=>(Array.isArray(keys)?keys:[keys]).forEach(k=>delete store[k])}},tabs:{remove:async id=>removed.push(id)}};
let locked=false;const navigator={locks:{request:async(n,o,f)=>{if(locked)return f(null);locked=true;try{return await f({});}finally{locked=false;}}}};
const ctx=vm.createContext({TFCore:C,chrome,navigator,crypto:require('node:crypto').webcrypto,AbortController,structuredClone,setTimeout,clearTimeout,setInterval,clearInterval,Date,console});vm.runInContext(fs.readFileSync(root+'/multi-scanner/engine.js','utf8'),ctx);const Engine=ctx.TFEngine;
const profile={summary:'15x (-1)\nConsecutive Loss',score:'Profit Factor\n1.6\n2/4\nRecovery Factor\n4.11\n2/4\nStatus Channel\nPriority Channel'};
const cards=Array.from({length:501},(_,i)=>({id:String(i),name:'Analyst '+i,url:'https://account.tradersfamily.id/channels/'+i+'/',level:'Master',losing:i<500?0:1,denominator:12}));
function setup(engine,inventory=cards){engine.navigate=async()=>{engine.check();engine.tabId=17;};let batch=0,range;const dom=async(stage,arg)=>{engine.check();if(stage==='inventoryStart')return {rows:inventory.slice(0,36)};if(stage==='inventoryMore'){batch++;return {rows:inventory.slice(0,36*(batch+1)),done:batch*36+36>=inventory.length,endEvidence:'fixture'};}if(stage==='portfolio')return {months:12};if(stage==='statistics')return {rows:[],oldest:'2024-01'};if(stage==='summary')return {summary:profile.summary};if(stage==='score')return {score:profile.score};if(stage==='historyStart'){range=arg;return {rows:[]};}if(stage==='historyMore'){const [y,m,d]=range.start.split('-');return {rows:range.start===engine.job.ranges[0].start?Array.from({length:10},(_,i)=>({signal_id:String(i),symbol:'XAUUSD',result:'-150.0 Pips',closed_at_wib:`${d}-${m}-${y}`})):[],done:true,endEvidence:'fixture'};}throw Error(stage);};engine.dom=dom;return dom;}
(async()=>{
  const e=new Engine(()=>{});setup(e);await e.start(C.defaults);assert.equal(e.job.cursor,501);assert.equal(e.job.results.length,1);assert.equal(e.job.skipped.length,500);assert.equal(e.job.status,'complete');assert.equal(e.job.progress.fraction,1);
  delete store.tfMultiJobV419;const paused=new Engine(()=>{}),original=setup(paused,[cards[500]]);let reached;const entering=new Promise(r=>reached=r);paused.dom=async(stage,arg)=>{if(stage==='historyMore'){reached();return paused.guarded(new Promise(()=>{}));}return original(stage,arg);};const run=paused.start(C.defaults);await entering;await paused.interrupt('paused');await run;assert.equal(paused.job.status,'paused');assert.equal(paused.job.cursor,0);assert.equal(paused.job.results.length,0);paused.dom=setup(paused,[cards[500]]);await paused.resume(paused.job);assert.equal(paused.job.status,'complete');assert.equal(paused.job.results.length,1);assert.equal(paused.job.cursor,1);
  delete store.tfMultiJobV419;const stopped=new Engine(()=>{}),normal=setup(stopped,[cards[500]]);let entered;const waiting=new Promise(r=>entered=r);stopped.dom=async(stage,arg)=>{if(stage==='summary'){entered();return stopped.guarded(new Promise(()=>{}));}return normal(stage,arg);};const stopRun=stopped.start(C.defaults);await waiting;await stopped.interrupt('stopped');await stopRun;assert.equal(stopped.job.status,'stopped');assert.equal(stopped.job.results.length,0);assert.equal(stopped.job.cursor,0);stopped.dom=setup(stopped,[cards[500]]);await stopped.resume(stopped.job);assert.equal(stopped.job.status,'complete');assert.equal(stopped.job.cursor,1);assert.equal(stopped.job.results.length,1);assert.ok(removed.length>=3);assert.ok(removed.every(id=>id===17));
  delete store.tfMultiJobV419;const partial=new Engine(()=>{}),partialDom=setup(partial,[cards[500],{...cards[500],id:'501',name:'Second',url:'https://account.tradersfamily.id/channels/501/'}]);let second;const secondEntered=new Promise(r=>second=r);partial.dom=async(stage,arg)=>{if(stage==='summary'&&partial.job.cursor===1){second();return partial.guarded(new Promise(()=>{}));}return partialDom(stage,arg);};const partialRun=partial.start(C.defaults);await secondEntered;await partial.interrupt('stopped',{action:'stop',source:'test-stop-button',at:Date.now()});await partialRun;assert.equal(partial.job.results.length,1);assert.equal(partial.job.cursor,1);assert.equal(partial.job.lastControl.source,'test-stop-button');partial.dom=setup(partial,[cards[500],{...cards[500],id:'501',name:'Second',url:'https://account.tradersfamily.id/channels/501/'}]);await partial.resume(partial.job);assert.equal(partial.job.cursor,2);assert.equal(partial.job.results.length,2);assert.equal(new Set(partial.job.results.map(r=>r.url)).size,2);
  for(const on of [true,false]){delete store.tfMultiJobV419;const dynamic=new Engine(()=>{}),normal=setup(dynamic,[cards[500]]);dynamic.dom=async(stage,arg)=>{const packet=await normal(stage,arg);if(stage==='historyMore')packet.rows=packet.rows.map((r,i)=>({...r,result:('-'+(150+i)+' Pips')}));return packet;};await dynamic.start({...C.defaults,requireFixed:on});assert.equal(dynamic.job.status,'complete');assert.equal(dynamic.job.results.length,on?0:1);if(!on){assert.equal(dynamic.job.results[0].sl,null);assert.equal(dynamic.job.results[0].slFixedChecked,false);}}
  delete store.tfMultiJobV419;const repeatOff=new Engine(()=>{}),repeatNormal=setup(repeatOff,[cards[500]]);repeatOff.dom=async(stage,arg)=>{const packet=await repeatNormal(stage,arg);if(stage==='historyMore')packet.rows=packet.rows.map((r,i)=>({...r,result:('-'+(150+i)+' Pips')}));return packet;};await repeatOff.start({...C.defaults,requireFixed:true,fixedRepeatsOn:false});assert.equal(repeatOff.job.status,'complete');assert.equal(repeatOff.job.results.length,0);assert.equal(repeatOff.job.filters.fixedRepeatsOn,true);
  console.log('PASS: ON rejects dynamic; OFF allows without claiming fixed; JS syntax, 501 cards, per-card progress, immediate cancellation of pending History/Profile, Pause/Resume with no duplicates, explicit Resume after Stop completes unfinished card, only owned tab closed.');
})().catch(e=>{console.error(e);process.exitCode=1;});

const C432=require(path.resolve(root,'multi-scanner/core.js'));for(const spec of C432.scoreFields)assert.deepStrictEqual(C432.defaults[spec.key],['profitFactorAllowed','recoveryAllowed'].includes(spec.key)?[1,2]:[]);const fixture='Level\nMaster\n2/4\nStatus Channel\nPriority Channel\n4/4\nSubscriber\n45 Investor\n1/4\nProfit Factor\n1.6\n2/4\nMthly. Loss Ratio\n17.5%\n3/4\nProfit Months\n5 Months\n3/4\nRecovery Factor\n4.11\n2/4';const detail=C432.scoreDetails(fixture);assert.deepStrictEqual(C432.scoreFields.map(s=>detail[s.field]),[2,4,1,2,3,3,2]);assert.strictEqual(C432.accepted(detail,C432.defaults),null);assert(C432.accepted(detail,{monthlyLossAllowed:[1]}));assert.deepStrictEqual(C432.sortRows([{status:'Prospect',profitFactor:9,name:'C'},{status:'Priority',profitFactor:2,name:'B'},{status:'Priority',profitFactor:4,name:'A'}]).map(r=>r.name),['A','B','C']);console.log('PASS: seven scoring fields, PF/RF defaults 1/4 and 2/4, selection filter, default status plus Profit Factor sort.');


;(()=>{
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').resolve(root,'multi-scanner/engine.js'),'utf8');
async function test(mode){let now=0,updates=0,creates=0,closed=[],probes=0,logs=[];const url='https://account.tradersfamily.id/channels/browse/?';
const chrome={storage:{local:{set:async()=>{}}},tabs:{getCurrent:async()=>({windowId:8}),create:async props=>{assert.equal(props.windowId,8);return {id:++creates}},remove:async id=>closed.push(id),update:async()=>{updates++},get:async()=>{now+=30000;return {status:mode==='login'?'complete':'loading',url:mode==='login'?'https://account.tradersfamily.id/login/':url}}},scripting:{executeScript:async packet=>{probes++;if(mode==='cancel'){engine.interrupted='stopped';engine.abort.abort();return [];}const result=vm.runInNewContext('('+packet.func.toString()+')(expected)',{expected:url,URL,location:{origin:'https://account.tradersfamily.id',pathname:mode==='wrong'?'/channels/123/':'/channels/browse/'},document:{readyState:'interactive',querySelector:()=>mode==='retry'&&creates===1?null:{}}});return [{result}]}}};
const ctx=vm.createContext({chrome,AbortController,Date:{now:()=>now},URL,setTimeout:fn=>{fn();return 1},clearTimeout});vm.runInContext(source,ctx);const engine=new ctx.TFEngine(()=>{});engine.abort=new AbortController();engine.log=async s=>logs.push(s);
if(['wrong','login','cancel'].includes(mode)){await assert.rejects(engine.navigate(url),mode==='wrong'?/2 percobaan/:mode==='login'?/Login TF/:/Dihentikan/);if(mode==='wrong')assert.equal(creates,2);}else{await engine.navigate(url);assert.ok(probes);assert.equal(creates,mode==='retry'?2:1);assert.equal(updates,0);if(mode==='retry')assert.deepStrictEqual(closed,[1]);assert.ok(logs.some(s=>s.includes('Isi halaman')));}
}
(async()=>{for(const mode of ['ready','retry','wrong','login','cancel'])await test(mode);console.log('PASS: interactive DOM while tab loading, one automatic retry, wrong-page rejection, login redirect and immediate Stop.');})().catch(e=>{console.error(e);process.exitCode=1});

})();

;(()=>{
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');const C=require(require('node:path').resolve(root,'multi-scanner/core.js'));let reads=0,reloads=0;
const profile={summary:'14x (-$51,912)\nConsecutive Loss',score:'Profit Factor\n1.22\n1/4\nRecovery Factor\n2.77\n2/4\nStatus Channel\nBasic Channel'};
const chrome={tabs:{get:async()=>({url:'https://account.tradersfamily.id/channels/271145/'})},scripting:{executeScript:async p=>p.files?[]:[{result:{ok:true,data:++reads===1?{summary:'',score:'Overview\n FETCHING CONTENT . . .'}:profile}}]}};
const ctx=vm.createContext({TFCore:C,chrome,AbortController,setTimeout:fn=>{fn();return 1},clearTimeout});vm.runInContext(fs.readFileSync(require('node:path').resolve(root,'multi-scanner/engine.js'),'utf8'),ctx);const e=new ctx.TFEngine(()=>{});e.abort=new AbortController();e.tabId=1;e.log=async()=>{};e.navigate=async url=>{assert.ok(url.includes('271145'));reloads++};
(async()=>{const value=await e.dom('profile');assert.equal(C.summary(value.summary),14);assert.equal(reads,2);assert.equal(reloads,1);console.log('PASS: empty Summary/Score cannot be accepted; reload preserves analyst URL and recovers populated profile.');})().catch(err=>{console.error(err);process.exitCode=1});

})();
