class TFEngine{
  constructor(change){this.change=change;this.running=false;this.abort=null;this.interrupted=null;this.tabId=null;}
  check(){if(this.abort?.signal.aborted)throw Object.assign(Error(this.interrupted==='stopped'?'Dihentikan paksa.':'Scan dijeda.'),{interrupted:this.interrupted});}
  async guarded(promise){this.check();const signal=this.abort?.signal;if(!signal)return promise;let handler;const cancelled=new Promise((_,reject)=>{handler=()=>reject(Object.assign(Error(this.interrupted==='stopped'?'Dihentikan paksa.':'Scan dijeda.'),{interrupted:this.interrupted}));signal.addEventListener('abort',handler,{once:true});});try{return await Promise.race([promise,cancelled]);}finally{signal.removeEventListener('abort',handler);}}
  async save(){this.job.heartbeatAt=Date.now();await chrome.storage.local.set({tfMultiJobV419:this.job});this.change(this.job);}
  async phase(name,index,fraction,message,inside){this.check();inside=inside??(fraction===0?false:this.job.progress?.inside||false);this.job.progress={name,index,fraction,message,inside};await this.save();}
  async log(message){this.job.logs.push(new Date().toLocaleTimeString('id-ID')+' '+message);this.job.logs=this.job.logs.slice(-300);await this.save();}
  async interrupt(status){if(!this.running)return;this.interrupted=status;this.abort.abort();const id=this.tabId;this.tabId=null;if(Number.isInteger(id)){try{await chrome.tabs.remove(id);}catch{}}}
  async navigate(url){this.check();if(!this.tabId){const controller=this.abort;const tab=await this.guarded(chrome.tabs.create({url,active:false}).then(async tab=>{if(controller.signal.aborted){await chrome.tabs.remove(tab.id);throw Error('Navigasi dibatalkan.');}return tab;}));this.tabId=tab.id;await chrome.storage.local.set({tfMultiOwnedTabV419:tab.id});}else await this.guarded(chrome.tabs.update(this.tabId,{url}));const deadline=Date.now()+60000;while(Date.now()<deadline){this.check();const tab=await this.guarded(chrome.tabs.get(this.tabId));if(tab.status==='complete'){if(!tab.url?.startsWith('https://account.tradersfamily.id/channels/'))throw Error('Login TF diperlukan.');return;}await this.guarded(new Promise(r=>setTimeout(r,200)));}throw Error('Navigasi TF terlalu lama.');}
  async dom(stage,arg){this.check();await this.guarded(chrome.scripting.executeScript({target:{tabId:this.tabId},files:['multi-scanner/collector.js']}));const [r]=await this.guarded(chrome.scripting.executeScript({target:{tabId:this.tabId},func:async(stage,arg)=>await globalThis.tfScanDOM(stage,arg),args:[stage,arg||{}]}));this.check();if(!r||r.result===undefined)throw Error('Tidak ada hasil DOM.');return r.result;}
  async start(filters){return navigator.locks.request('tf-multi-runner-v419',{ifAvailable:true},async lock=>{if(!lock)throw Error('Runner aktif di dashboard lain.');const state=await chrome.storage.local.get(['tfMultiJobV419','tfScanInProgress']);if(state.tfScanInProgress)throw Error('Batch scan utama masih berjalan.');if(state.tfMultiJobV419&&['running','paused','error'].includes(state.tfMultiJobV419.status))throw Error('Gunakan Resume atau Stop untuk scan sebelumnya.');TFCore.validate(filters);if(state.tfMultiJobV419)await chrome.storage.local.set({['tfMultiArchiveV419-'+state.tfMultiJobV419.id]:state.tfMultiJobV419});const end=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});this.job={id:crypto.randomUUID(),status:'running',filters:structuredClone(filters),asOf:end,ranges:TFCore.ranges(end,filters.historyMonths),inventory:[],inventoryComplete:false,cursor:0,results:[],skipped:[],evidence:[],logs:[],createdAt:new Date().toISOString()};return this.runLocked();});}
  async resume(job){return navigator.locks.request('tf-multi-runner-v419',{ifAvailable:true},async lock=>{if(!lock)throw Error('Runner aktif di dashboard lain.');const state=await chrome.storage.local.get(['tfMultiJobV419','tfScanInProgress']);if(state.tfScanInProgress)throw Error('Batch scan utama masih berjalan.');this.job=state.tfMultiJobV419||job;if(!this.job||['complete','stopped'].includes(this.job.status))return;return this.runLocked();});}
  async runLocked(){this.running=true;this.abort=new AbortController();this.interrupted=null;this.job.status='running';delete this.job.error;const heartbeat=setInterval(()=>{if(this.running&&!this.abort.signal.aborted)chrome.storage.local.set({tfMultiHeartbeatV419:Date.now()});},3000);await chrome.storage.local.set({tfMultiHeartbeatV419:Date.now()});await this.save();try{
    const f=this.job.filters;
    if(!this.job.inventoryComplete){await this.log('Memuat seluruh card sesuai filter…');await this.navigate('https://account.tradersfamily.id/channels/browse/?');let batch=await this.dom('inventoryStart',f);this.check();this.job.inventory=batch.rows;await this.save();while(true){batch=await this.dom('inventoryMore');this.check();this.job.inventory=batch.rows;await this.save();if(batch.done){this.job.inventoryComplete=true;this.job.inventoryEnd=batch.endEvidence;await this.save();break;}}await this.log(this.job.inventory.length+' card ditemukan.');}
    while(this.job.cursor<this.job.inventory.length){this.check();const card=this.job.inventory[this.job.cursor],index=this.job.cursor+1;await this.phase(card.name,index,0,'Memeriksa Level dan Losing Month');
      if(!TFCore.cardAllowed(card,f)){this.check();this.job.skipped.push({id:card.id,name:card.name,reason:'Level / Losing Month tidak sesuai'});this.job.cursor++;await this.phase(card.name,index,1,'Skip: Level / Losing Month');continue;}
      await this.phase(card.name,index,.05,'Membuka card analis');await this.navigate(card.url);await this.phase(card.name,index,.1,'Summary ALL dan Score',true);const profile=await this.dom('profile');const consecutive=TFCore.summary(profile.summary),score=TFCore.score(profile.score);let rejection=null;if(consecutive>f.maxConsecutive)rejection='Consecutive Loss '+consecutive;if(!f.recoveryAllowed.includes(score.recoveryScore))rejection='Recovery Factor '+score.recoveryScore+'/4';if(f.statuses.length&&!f.statuses.includes(score.status))rejection='Status '+score.status+' tidak sesuai';const evidence={card,profile,consecutive,...score,windows:[]};await this.phase(card.name,index,.3,'Summary dan Score selesai');
      if(!rejection){for(let w=0;w<this.job.ranges.length;w++){const range=this.job.ranges[w],fraction=.3+.6*w/this.job.ranges.length;await this.phase(card.name,index,fraction,`History ${f.pair}: ${range.start} s/d ${range.end}`);let batch=await this.dom('historyStart',{...range,pair:f.pair});if(batch.unavailable){rejection='Pair '+f.pair+' tidak tersedia';break;}let rows=batch.rows;while(true){await this.phase(card.name,index,fraction,`History ${w+1}/${this.job.ranges.length} · ${rows.length} signal dimuat`);batch=await this.dom('historyMore');rows=batch.rows;if(batch.done)break;}for(const row of rows){const date=TFCore.closedDate(row.closed_at_wib);if(/Pips/i.test(row.result)&&(!date||date<range.start||date>range.end))throw Error('Closed at di luar rentang.');if(row.symbol!==f.pair)throw Error('Pair history tidak sesuai.');}this.check();evidence.windows.push({range,rows,endEvidence:batch.endEvidence});this.job.currentEvidence=evidence;await this.phase(card.name,index,.3+.6*(w+1)/this.job.ranges.length,`History ${w+1}/${this.job.ranges.length} selesai`);}
        if(!rejection){await this.phase(card.name,index,.95,'Menghitung pips negatif yang sama persis');const matches=TFCore.fixed(evidence.windows.flatMap(w=>w.rows),f.pair,f.minRepeats,this.job.ranges[0].start,this.job.asOf);evidence.fixedMatches=matches;this.check();if(!matches.length)rejection='Tidak ada pips negatif sama persis sebanyak '+f.minRepeats+' kejadian';else this.job.results.push({name:card.name,url:card.url,pair:f.pair,sl:matches[0].value,repeat:matches[0].count,consecutive,profitFactor:score.profitFactor,losing:`${card.losing}/${card.denominator}`,level:card.level,status:score.status,recoveryScore:score.recoveryScore});}}
      this.check();if(rejection)this.job.skipped.push({id:card.id,name:card.name,reason:rejection});this.job.evidence.push(evidence);delete this.job.currentEvidence;this.job.cursor++;await this.phase(card.name,index,1,rejection?'Skip: '+rejection:'Lolos · pemeriksaan selesai');await this.log(card.name+' · '+(rejection?'skip: '+rejection:'LOLOS'));}
    this.check();this.job.status='complete';this.job.finishedAt=new Date().toISOString();await this.log('Semua '+this.job.inventory.length+' card selesai dievaluasi.');
  }catch(e){this.job.status=this.interrupted||e.interrupted||'error';this.job.error=this.job.status==='stopped'?'Dihentikan paksa. Hasil analis selesai tetap tersimpan.':this.job.status==='paused'?'Dijeda. Resume mengulang card yang belum selesai.':e.message;await this.log(this.job.error);}finally{clearInterval(heartbeat);this.running=false;await chrome.storage.local.set({tfMultiHeartbeatV419:0});const id=this.tabId;this.tabId=null;if(Number.isInteger(id)){try{await chrome.tabs.remove(id);}catch{}}await chrome.storage.local.remove('tfMultiOwnedTabV419');await this.save();}}
}
globalThis.TFEngine=TFEngine;
