(async()=>{
  if(window.tfIntegrityReady&&!(await window.tfIntegrityReady))return;
  document.body.innerHTML=`<div class="dashboard"><header><img src="../icon32.png" alt="TF"><div><h1>TF Multi-Link Dashboard</h1><small>Scrape Multi-Link Analis · REV454</small></div></header><main><h1 class="print-title">TF Multi-Link Dashboard — Hasil scan</h1><div class="stats" id="stats"></div><div class="actions"><button id="submit">Submit</button><button id="pause" class="secondary" disabled>Pause</button><button id="xlsx" class="secondary">Export Excel</button><button id="pdf" class="secondary">Export PDF</button><button id="txt" class="secondary">Export TXT</button><button id="evidence" class="secondary">Bukti JSON</button></div><div class="progress-card"><p id="overall-label" class="notice">Jumlah card belum dihitung.</p><div id="card-progress" hidden><div class="progress-label"><span id="card-label">Card analis</span><span id="card-percent">0%</span></div><div class="progress-track"><div class="progress-fill" id="card-fill"></div></div></div><p id="card-stage" class="notice">Belum berjalan.</p></div><p class="notice" id="progress">Belum ada scan.</p><section><div class="table-wrap"><table><thead id="result-head"></thead><tbody id="results"></tbody></table></div></section><section class="filter-summary"><h2>Filter yang dipakai saat scan</h2><div class="filter-summary-grid" id="filter-summary"></div></section><section class="audit"><h2>Catatan pemeriksaan</h2><pre id="filter-info" hidden></pre><div class="logs" id="logs"></div></section></main></div>`;
  const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let job=null,lastResults='',showFixed=true,displayFilters=TFCore.defaults,sortKey='status',sortDirection='desc',sortedResults=[],startLockedUntil=0;const engine=new TFEngine(render);
  function render(j){job=j;paintFilterSummary(j?.filters);if(!j){lastResults='';sortedResults=[];sortKey='status';sortDirection='desc';$('#stats').innerHTML=[['Total card',0],['Diperiksa',0],['Lolos',0],['Skip',0]].map(([label,n])=>`<div class="stat"><small>${label}</small><b>${n}</b></div>`).join('');$('#submit').disabled=false;$('#submit').textContent='Submit';$('#submit').classList.remove('stop');$('#pause').textContent='Pause';$('#pause').disabled=true;TFMultiProgress.paint(null);$('#progress').textContent='Belum ada scan.';$('#filter-info').textContent='';$('#logs').innerHTML='';paintTable({results:[],evidence:[],filters:displayFilters});return;}$('#stats').innerHTML=[['Total card',j.isPreview?'—':j.inventoryComplete?j.inventory.length:'Memuat…'],['Diperiksa',j.isPreview?'—':j.cursor],['Lolos',j.isPreview?'—':j.results.length],['Skip',j.isPreview?'—':j.skipped.length]].map(([label,n])=>`<div class="stat"><small>${label}</small><b>${n}</b></div>`).join('');TFMultiProgress.paint(j);const active=['running','paused','error'].includes(j.status);$('#submit').disabled=Date.now()<startLockedUntil;$('#submit').textContent=active?'Stop':'Submit';$('#submit').classList.toggle('stop',active);$('#pause').textContent=j.status==='running'?'Pause':'Resume';$('#pause').disabled=!active&&!(j.status==='stopped'&&(!j.inventoryComplete||j.cursor<j.inventory.length));const label={running:'Sedang scan',paused:'Dijeda',stopped:'Dihentikan',error:'Error',complete:'Selesai'}[j.status];$('#progress').textContent=`${j.isPreview?'Pratinjau tampilan — bukan hasil scan terbaru':label} · ${j.filters.pair} · ${j.ranges[0].start} s/d ${j.asOf}${j.error?'\n'+j.error:''}`;paintTable(j);$('#filter-info').textContent=JSON.stringify(j.filters,null,2);$('#logs').innerHTML=j.logs.map(s=>`<p>${esc(s)}</p>`).join('');}
  function paintFilterSummary(filters){
    const node=$('#filter-summary');if(!filters){node.innerHTML='<p class="notice">Belum ada scan. Filter akan ditampilkan setelah scan dimulai.</p>';return;}
    const f={...TFCore.defaults,...filters},empty=v=>v===undefined||v===null||v==='',num=v=>empty(v)?'Tidak dibatasi':String(v),list=(v,fallback)=>Array.isArray(v)&&v.length?v.join(', '):fallback;
    const bounds=(a,b,unit)=>empty(a)&&empty(b)?'Tidak dibatasi':empty(a)?'Maksimum '+b+unit:empty(b)?'Minimum '+a+unit:a+' – '+b+unit;
    const months=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
    const selectedMonths=[...(f.survivedMonths||[])].sort().map(x=>{const [y,m]=String(x).split('-');return (months[Number(m)-1]||m)+' '+y;}).join(', ');
    const statuses=(f.statuses||[]).map(x=>x==='Basic'?'Basic Channel':x+' Channel');
    const left=[['Pair',f.pair],['Level',list(f.levels,'Semua level')],['Status channel',list(statuses,'Semua status')],['Score',bounds(f.scoreMin,f.scoreMax,'')],['Data Summary',Number(f.summary)===12?'1 tahun terakhir':f.summary+' bulan terakhir'],['Sort by',({medal:'Medal',score:'Score',probability:'Probability',profit:'Profit'})[f.sort]||f.sort],['Losing Month maksimum',num(f.losingMax)+' bulan'],['Losing Month yang diterima',list(f.losingAllowed,'Tidak difilter')+' bulan'],['Probability',bounds(f.probabilityMin,f.probabilityMax,'%')],['Average TP',bounds(f.tpMin,f.tpMax,' pips')],['Risk : Reward',empty(f.risk)&&empty(f.reward)?'Tidak dibatasi':num(f.risk)+' : '+num(f.reward)],['Avg. Monthly Profit',bounds(f.profitMin,f.profitMax,' pips')],['Max. Loss',empty(f.maxLoss)?'Tidak dibatasi':f.maxLoss+'%']];
    const right=[['Minimum Portofolio',f.minimumPortfolioOn?'ON · minimum '+f.minimumPortfolioMonths+' bulan':'OFF · dilewati'],['Survived Month',f.survivedOn?'ON · wajib profit > 0 pips setiap bulan':'OFF · dilewati'],['Bulan yang dipilih',f.survivedOn?(selectedMonths||'Belum dipilih'):'Tidak digunakan (OFF)'],['Consecutive Loss maksimum',f.maxConsecutive+'x'],['Filter SL Fixed',f.requireFixed?'ON · periksa History Signal':'OFF · History Signal dilewati'],['History Signal',f.requireFixed?f.historyMonths+' bulan terakhir (menyesuaikan data tersedia)':'Tidak digunakan (OFF)'],['SL pips yang sama · minimum',f.requireFixed?f.minRepeats+' kejadian':'Tidak digunakan (OFF)'],...TFCore.scoreFields.map(x=>[x.label+' · skor yang diterima',Array.isArray(f[x.key])&&f[x.key].length?f[x.key].map(n=>n+'/4').join(', '):'Tidak difilter'])];
    node.innerHTML=[left,right].map((rows,i)=>'<div class="filter-summary-table"><table aria-label="Ringkasan filter '+(i?'kanan':'kiri')+'"><thead><tr><th>Filter</th><th>Nilai</th></tr></thead><tbody>'+rows.map(([k,v])=>'<tr><td>'+esc(k)+'</td><td>'+esc(v)+'</td></tr>').join('')+'</tbody></table></div>').join('');
  }
  function paintTable(j){
    const specs=TFCore.scoreFields.filter(spec=>(displayFilters[spec.key]||[]).length);
    const columns=[{key:'url',label:'Link',sort:false},{key:'name',label:'Nama Analis'},{key:'pair',label:'Pair'},{key:'sl',label:'SL Fixed Pips'},...(showFixed?[{key:'repeat',label:'SL Fixed pips<br>Count ('+esc(j.filters.historyMonths||6)+' Mth)'}]:[]),{key:'consecutive',label:'Consecutive loss'},...(specs.some(s=>s.key==='profitFactorAllowed')?[{key:'profitFactor',label:'Profit Factor'}]:[]),...specs.filter(s=>s.key!=='profitFactorAllowed').map(s=>({key:s.field,label:s.label+'<br>Skor',metric:true})),{key:'losing',label:'Losing Month'},{key:'level',label:'Level'},{key:'status',label:'Centang'}];
    const signature=JSON.stringify([j.results,specs.map(s=>s.key),showFixed,sortKey,sortDirection,j.evidence?.length]);if(signature===lastResults)return;lastResults=signature;
    sortedResults=TFCore.sortRows(j.results.map(r=>{const raw=j.evidence?.find(e=>e.card?.url===r.url)?.profile?.score;return {...(raw?TFCore.scoreDetails(raw):{}),...r};}),sortKey,sortDirection);
    $('#result-head').innerHTML='<tr>'+columns.map(c=>`<th ${c.sort===false?'':`data-sort="${c.key}" tabindex="0" aria-sort="${sortKey===c.key?(sortDirection==='desc'?'descending':'ascending'):'none'}" style="cursor:pointer"`}>${c.label}${c.sort===false?'':` <span aria-hidden="true" style="color:${sortKey===c.key?'#38bdf8':'#94a3b8'}"><span style="opacity:${sortKey===c.key&&sortDirection==='asc'?1:.35}">▲</span><span style="opacity:${sortKey!==c.key||sortDirection==='desc'?1:.35}">▼</span></span>`}</th>`).join('')+'</tr>';
    $('#results').innerHTML=sortedResults.map((r,i)=>'<tr>'+columns.map(c=>{if(c.key==='url')return `<td class="link-cell"><button class="copy-link secondary" data-row="${i}">Copy Link</button></td>`;if(c.key==='name')return `<td><a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.name)}</a></td>`;if(c.key==='status')return `<td class="status ${esc(r.status)}">${r.status==='Basic'?'Basic Channel':'✓ '+esc(r.status)}</td>`;const value=c.key==='sl'&&r.sl==null?'Filter OFF':c.key==='repeat'&&r.slFixedChecked===false?'—':c.metric?(r[c.key]===undefined?'—':r[c.key]+'/4'):r[c.key]??'—';return `<td>${esc(value)}</td>`;}).join('')+'</tr>').join('');
  }
  function changeSort(header){if(!header?.dataset.sort)return;const key=header.dataset.sort;sortDirection=sortKey===key?(sortDirection==='desc'?'asc':'desc'):'desc';sortKey=key;if(job)paintTable(job);}
  $('#result-head').onclick=e=>changeSort(e.target.closest('th[data-sort]'));
  $('#result-head').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();changeSort(e.target.closest('th[data-sort]'));}};
  function showError(e){$('#progress').textContent=e.message;}
  async function control(action){const response=await chrome.runtime.sendMessage({type:'TF_MULTI_CONTROL',source:'dashboard-'+action+'-button',action,jobId:job?.id});if(!response?.ok)throw Error(response?.error||'Kontrol tidak merespons.');}
  $('#submit').onclick=async event=>{if(event.detail>1||Date.now()<startLockedUntil)return;startLockedUntil=Date.now()+1500;$('#submit').disabled=true;setTimeout(()=>{if(job)render(job);else $('#submit').disabled=false;},1550);try{if(job&&['running','paused','error'].includes(job.status))return await control('stop');const s=await chrome.storage.local.get('tfMultiFiltersV419');await engine.start(s.tfMultiFiltersV419||TFCore.defaults);}catch(e){showError(e);}};
  $('#pause').onclick=()=>control(job?.status==='running'?'pause':'resume').catch(showError);
  $('#results').onclick=async event=>{const button=event.target.closest('button[data-row]');if(!button)return;try{await navigator.clipboard.writeText(sortedResults[Number(button.dataset.row)].url);button.textContent='Link Copied!';clearTimeout(button.tfCopyTimer);button.tfCopyTimer=setTimeout(()=>{button.textContent='Copy Link';},2000);}catch{button.textContent='Copy failed';setTimeout(()=>button.textContent='Copy Link',2000);}};
  const exportAction=fn=>async()=>{try{if(!job?.results.length)throw Error('Belum ada hasil lolos.');await fn(job.results);}catch(e){showError(e);}};
  $('#xlsx').onclick=exportAction(rows=>TFExport.download(TFExport.xlsx(rows),'tf-multi-link-hasil.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'));
  $('#pdf').onclick=exportAction(()=>window.print());$('#txt').onclick=exportAction(rows=>TFExport.download(rows.map(r=>r.name+' : '+r.url).join('\r\n'),'tf-multi-link-hasil.txt','text/plain;charset=utf-8'));$('#evidence').onclick=()=>{if(job)TFExport.download(JSON.stringify(job,null,2),'tf-multi-link-bukti.json','application/json');};
  const hasChrome=typeof chrome!=='undefined'&&!!chrome.storage;
  if(!hasChrome){$('#submit').disabled=true;$('#progress').textContent='Pratinjau tampilan — runner aktif setelah extension dipasang.';if(globalThis.TFMultiPreviewJob)render(globalThis.TFMultiPreviewJob);return;}
  chrome.storage.onChanged.addListener((c,area)=>{if(area!=='local')return;if(c.tfMultiFiltersV419?.newValue){displayFilters={...TFCore.defaults,...c.tfMultiFiltersV419.newValue};showFixed=displayFilters.requireFixed!==false;if(job)render(job);}if(Object.prototype.hasOwnProperty.call(c,'tfMultiJobV419'))render(c.tfMultiJobV419.newValue||null);const cmd=c.tfMultiCommandV419?.newValue;if(cmd&&cmd.jobId===job?.id){if(cmd.action==='pause'||cmd.action==='stop'){engine.interrupt(cmd.action==='stop'?'stopped':'paused',cmd);}else if(cmd.action==='resume'&&!engine.running)engine.resume(job).catch(showError);}if(c.tfMultiPendingStartV419?.newValue)startPending();});
  async function startPending(){if(engine.running)return;const s=await chrome.storage.local.get(['tfMultiPendingStartV419','tfMultiFiltersV419']);if(!s.tfMultiPendingStartV419)return;await chrome.storage.local.set({tfMultiPendingStartV419:false});await engine.start(s.tfMultiFiltersV419||TFCore.defaults).catch(showError);}
  const s=await chrome.storage.local.get(['tfMultiJobV419','tfMultiCommandV419','tfMultiFiltersV419']);displayFilters={...TFCore.defaults,...(s.tfMultiFiltersV419||s.tfMultiJobV419?.filters||{})};showFixed=displayFilters.requireFixed!==false;if(s.tfMultiJobV419){job=s.tfMultiJobV419;render(job);if(job.status==='running'){await navigator.locks.request('tf-multi-runner-v419',{ifAvailable:true},async lock=>{if(lock){job.status='paused';job.error='Dashboard sebelumnya ditutup. Klik Resume untuk melanjutkan.';await chrome.storage.local.set({tfMultiJobV419:job,tfMultiHeartbeatV419:0});render(job);}});}if(s.tfMultiCommandV419?.action==='resume'&&s.tfMultiCommandV419.jobId===job.id&&['paused','error','stopped'].includes(job.status)&&Date.now()-s.tfMultiCommandV419.at<15000)engine.resume(job).catch(showError);}else render(null);await startPending();
  window.addEventListener('pagehide',()=>{if(engine.running){engine.interrupt('paused');chrome.runtime.sendMessage({type:'TF_MULTI_CONTROL',action:'pause',source:'dashboard-pagehide',jobId:job.id});}});
})();

