const fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{
const source=fs.readFileSync(process.env.TF_RISK_SOURCE,'utf8'),css=fs.readFileSync(process.env.TF_DASHBOARD_CSS,'utf8');const body=JSON.parse(source.match(/^document.body.innerHTML = (".*?");/s)[1]);const risk=source.slice(source.indexOf('let __tfLatestRiskState'),source.indexOf('// ===== END REV393'));
const browser=await chromium.launch({headless:true});try{const page=await browser.newPage({viewport:{width:1400,height:900}});await page.route('**/*',r=>r.abort());await page.setContent(body);await page.evaluate(()=>document.documentElement.dataset.tfServerAuthorized='1');await page.addStyleTag({content:css});
await page.evaluate(()=>{window.historySignals=Array.from({length:4348},(_,i)=>({analyst:'A',pair:'XAUUSD',pips:100,sortKey:Date.parse('2026-09-01')+i*1000}));document.querySelector('#summary-table tbody').innerHTML='<tr><td class="monthly-sticky-col-2">A</td><td>XAUUSD</td></tr>';document.querySelector('#drawdown-table tbody').innerHTML='<tr><td>▶</td><td>A</td></tr>';document.querySelector('#history-table tbody').innerHTML=Array.from({length:4348},(_,i)=>'<tr><td data-history-col="analyst">A</td><td data-history-col="pair">XAUUSD</td><td>'+i+'</td></tr>').join('');});
const headerBefore=await page.locator('#history-table th[data-history-col="analyst"]').evaluate(e=>getComputedStyle(e).textAlign);await page.evaluate(risk);await page.evaluate(()=>{window.passes=0;const original=tf_colorEveryRenderedAnalystName;tf_colorEveryRenderedAnalystName=(...args)=>{passes++;return original(...args)};});await page.waitForTimeout(500);const before=await page.evaluate(()=>passes);await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>passes),before,'observer must settle');
for(const selector of ['#summary-table tbody td:first-child','#history-table tbody td[data-history-col="analyst"]','#drawdown-table tbody td:nth-child(2)'])assert.equal(await page.locator(selector).first().evaluate(e=>getComputedStyle(e).textAlign),'left');assert.equal(await page.locator('#history-table th[data-history-col="analyst"]').evaluate(e=>getComputedStyle(e).textAlign),headerBefore);assert.equal(await page.locator('#tf-lot-sizing-title').textContent(),'Lot Sizing');assert.equal(await page.locator('#tf-lot-sizing-title').evaluate(e=>e.nextElementSibling.id),'analyst-filter-row');
const timing=await page.evaluate(()=>{const start=performance.now();for(let i=0;i<4348;i++)tf_getLatestRiskState('A');return performance.now()-start;});assert.ok(timing<2000,'row lookups should finish within 2 seconds');
const scroll=await page.locator('#history-table').evaluate(e=>{const div=e.closest('.table-scroll');div.style.maxHeight='300px';div.style.overflow='auto';div.scrollTop=100;div.scrollLeft=100;return {top:div.scrollTop,left:div.scrollLeft}});await page.waitForTimeout(200);assert.ok(scroll.top>0);console.log(JSON.stringify({rows:4348,lookupsMs:timing,observerPasses:before,alignment:'PASS',headers:'unchanged',scrollTop:scroll.top}));
}catch(e){throw e}finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
