const fs=require('fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{const source=fs.readFileSync(process.env.TF_SIDEBAR_SOURCE,'utf8'),base=fs.readFileSync(process.env.TF_BASE_SIDEBAR,'utf8');const header=s=>s.match(/^document.body.innerHTML = (".*?");/s);assert.equal(source.slice(header(source)[0].length),base.slice(header(base)[0].length),'all sidebar functions must remain byte-for-byte unchanged');
const browser=await chromium.launch({headless:true,channel:process.env.TF_BROWSER_CHANNEL||undefined});try{const page=await browser.newPage();await page.route('**/*',r=>r.abort());await page.setContent(JSON.parse(header(source)[1]));await page.evaluate(()=>{document.documentElement.dataset.tfServerAuthorized='1';document.querySelectorAll('body > *').forEach(el=>el.style.display='none');const main=document.getElementById('main-container');main.style.display='block';const container=document.getElementById('analyst-links-container');window.rows=[];const row=container.querySelector('.analyst-row');const names=['BHAGAWANTA','BullBearWave','Pips Gainer','Udine_Trader','nicangg','Very Long Analyst Name That Must Be Truncated'];container.innerHTML='';for(const name of names){const clone=row.cloneNode(true);clone.querySelector('.analyst-link-input').value='https://account.tradersfamily.id/channels/123456/';const btn=clone.querySelector('.analyst-paste-btn');btn.textContent=name;btn.title=name;btn.classList.add('tf-analyst-name-pill');const widget=clone.querySelector('.pair-multiselect');widget.classList.add('open');widget.querySelector('.pair-multiselect-label').textContent='5 Pairs';for(const label of widget.querySelectorAll('.pair-option')){const c=label.querySelector('input');c.checked=true;c.disabled=true;const x=document.createElement('button');x.textContent='×';x.className='tf-pair-delete408';x.style.cssText='font:inherit;padding:0 3px;margin-left:auto;flex:0 0 auto;border:0;background:transparent;color:#ef4444';label.appendChild(x);}container.appendChild(clone);window.rows.push(clone);}});await page.addStyleTag({path:process.env.TF_SIDEBAR_CSS});
for(const width of [320,400,436]){await page.setViewportSize({width,height:900});const result=await page.evaluate(()=>rows.map(row=>{const cells=[row.querySelector('.analyst-link-input'),row.querySelector('.analyst-paste-btn'),row.querySelector('.pair-multiselect'),row.querySelector('.analyst-remove-btn')];const dropdown=row.querySelector('.pair-multiselect-dropdown'),name=cells[1];return {x:cells.map(x=>Math.round(x.getBoundingClientRect().x)),width:cells.map(x=>Math.round(x.getBoundingClientRect().width)),menuWidth:dropdown.clientWidth,menuContent:dropdown.scrollWidth,horizontal:getComputedStyle(dropdown).overflowX,ellipsis:getComputedStyle(name).textOverflow,truncated:name.scrollWidth>name.clientWidth,locked:row.querySelector('.pair-option input').disabled};}));for(const row of result){assert.deepEqual(row.x,result[0].x);assert.deepEqual(row.width,result[0].width);assert.equal(row.menuContent,row.menuWidth,'pair menu must not overflow horizontally');assert.ok(row.menuWidth>=130);assert.equal(row.ellipsis,'ellipsis');assert.equal(row.locked,true);}assert.equal(result.at(-1).truncated,true);console.log('Fixed columns, analyst ellipsis and pair selector without horizontal overflow PASS at',width);}
await page.evaluate(()=>{rows[0].querySelector('.analyst-paste-btn').classList.add('tf-sidebar-risk-critical');rows[1].querySelector('.analyst-paste-btn').classList.add('tf-sidebar-risk-warning');rows[2].querySelector('.analyst-paste-btn').classList.add('tf-sidebar-risk-healthy');});
await page.waitForTimeout(250);
const boxes=await page.evaluate(()=>{const color=rows.slice(0,3).map(row=>{const s=getComputedStyle(row.querySelector('.analyst-paste-btn'));return {radius:s.borderRadius,border:s.borderTopColor,background:s.backgroundColor};});const remove=rows[0].querySelector('.analyst-remove-btn'),pair=rows[0].querySelector('.tf-pair-delete408');return {color,rowRadius:getComputedStyle(remove).borderRadius,pairRadius:getComputedStyle(pair).borderRadius,pairBorder:getComputedStyle(pair).borderTopWidth,pairWidth:pair.getBoundingClientRect().width};});
assert.equal(boxes.rowRadius,'8px');assert.equal(boxes.pairRadius,'3px');assert.equal(boxes.pairBorder,'1px');assert.equal(boxes.pairWidth,16);for(const box of boxes.color)assert.equal(box.radius,'8px');assert.match(boxes.color[0].border,/239, 68, 68/);assert.match(boxes.color[0].background,/239, 68, 68/);assert.match(boxes.color[1].border,/250, 204, 21/);assert.match(boxes.color[2].border,/34, 197, 94/);await page.evaluate(()=>rows[0].querySelector('.tf-pair-delete408').hidden=true);assert.equal(await page.locator('#analyst-links-container .tf-pair-delete408').first().isVisible(),false);console.log('Rounded name/row/pair delete boxes, hidden delete state and red/yellow/green status borders PASS');
await page.setViewportSize({width:436,height:900});await page.screenshot({path:'/tmp/layout410.png'});
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
