const fs=require('fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{const source=fs.readFileSync(process.env.TF_RISK_SOURCE||'assets/dashboard-mobile.js','utf8'),css=fs.readFileSync(process.env.TF_DASHBOARD_CSS||'assets/dashboard-original.css','utf8'),features=source.slice(source.indexOf('// REV412: shared dashboard presentation'));
const browser=await chromium.launch({headless:true,channel:process.env.TF_BROWSER_CHANNEL||undefined});try{const page=await browser.newPage();await page.route('**/*',r=>r.abort());await page.setContent('<div id="tf-balance-cards412" class="tf-balance-cards412"></div><table id="tf-users-mgmt-table"></table><span class="tf-isignal-subend" id="expiry"></span>');await page.addStyleTag({content:css});await page.evaluate(()=>{window.tf_applyLatestRiskColorOnly=()=>{};window.equityChartMode='line';window.draws=[];window.drawEquityCurve=()=>draws.push(tfEquityAnimation412?.progress??1);});await page.addScriptTag({content:features});
assert.equal(await page.locator('#tf-isignal-explainer412').count(),1);assert.ok((await page.locator('#tf-isignal-explainer412').textContent()).includes('mengatur Lot Size secara manual'));
for(const width of [390,1400]){await page.setViewportSize({width,height:844});const r=await page.locator('.tf-isignal-explainer-card412').boundingBox();assert.ok(r.width<=width && r.height<=844)}await page.locator('#tf-isignal-understand412').click();assert.equal(await page.locator('#tf-isignal-explainer412').count(),0);
await page.evaluate(()=>tf_renderBalanceCards412(5000,4800,false));assert.deepEqual(await page.locator('.tf-balance-value412').allTextContents(),['$5,000','$4,800','-$200','-4.00%']);assert.equal(await page.locator('.tf-balance-card412.neg').count(),2);await page.evaluate(()=>tf_renderBalanceCards412(5000,5325,false));assert.deepEqual((await page.locator('.tf-balance-value412').allTextContents()).slice(2),['+$325','+6.50%']);await page.evaluate(()=>tf_renderBalanceCards412(0,0,false));assert.equal((await page.locator('.tf-balance-value412').allTextContents())[3],'—');
await page.evaluate(()=>tf_applySubscription412(document.getElementById('expiry'),'2 Oktober 2020, 15:13'));assert.equal((await page.locator('#expiry').textContent()).trim(),'! 2 Oktober 2020, 15:13');assert.equal(await page.locator('#expiry').evaluate(e=>getComputedStyle(e).color),'rgb(239, 68, 68)');
await page.evaluate(()=>tf_animateEquity412());await page.waitForTimeout(450);const middle=await page.evaluate(()=>tfEquityAnimation412?.progress);assert.ok(middle>0 && middle<1);await page.evaluate(()=>tf_animateEquity412());await page.waitForTimeout(1050);assert.equal(await page.evaluate(()=>tfEquityAnimation412),null);assert.equal(await page.evaluate(()=>draws.at(-1)),1);await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>tf_animateEquity412());assert.equal(await page.evaluate(()=>tfEquityAnimation412),null);
if(process.env.TF_ISIGNAL_SOURCE){const isignal=fs.readFileSync(process.env.TF_ISIGNAL_SOURCE,'utf8');await page.setContent(JSON.parse(isignal.match(/^document.body.innerHTML = (".*?");/s)[1]));await page.evaluate(()=>{document.documentElement.dataset.tfServerAuthorized='1';window.historySignals=[{analyst:'Red Analyst',pair:'XAUUSD',pips:-100,sortKey:Date.parse('2026-09-01')},{analyst:'Red Analyst',pair:'XAUUSD',pips:-100,sortKey:Date.parse('2026-09-02')},{analyst:'Yellow Analyst',pair:'XAUUSD',pips:-100,sortKey:Date.parse('2026-09-02')},{analyst:'Green Analyst',pair:'XAUUSD',pips:100,sortKey:Date.parse('2026-09-02')}];});await page.addStyleTag({path:process.env.TF_ISIGNAL_CSS});const risk=isignal.slice(isignal.indexOf('let __tfLatestRiskState'),isignal.indexOf('// REV412: shared dashboard presentation'));await page.addScriptTag({content:risk});const colors=await page.evaluate(()=>['Red Analyst','Yellow Analyst','Green Analyst'].map(name=>{const a=document.createElement('a');a.className='tf-users-analyst-link';a.dataset.analyst=name;a.textContent=name;document.body.appendChild(a);tf_applyLatestRiskColorOnly(a,name,null);return getComputedStyle(a).color}));assert.deepEqual(colors,['rgb(239, 68, 68)','rgb(250, 204, 21)','rgb(34, 197, 94)']);console.log('Actual iSignal bundle analyst risk colors PASS');}
console.log('Balance PnL cards, subscription !, responsive iSignal explanation, cancellable reveal and reduced motion PASS');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
