const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {test}=require('node:test');
function harness(){const c={console,crypto:require('node:crypto').webcrypto,TextEncoder,TextDecoder,Uint8Array,Date,Map,setTimeout,clearTimeout,AbortController,btoa,atob};vm.createContext(c);let s=fs.readFileSync('deliverables/Cloudflare_Device_API_REV373_ACTIVATION_FIX.js','utf8').replace('export default','const workerDefault =').replace(/export class /g,'class ');vm.runInContext(s,c);c.license={valid:true,licenseId:'L',deviceType:'DESKTOP',credentials:{},activeDeviceId:'OLD',activePublicKey:'OLDKEY'};c.receipt={valid:true,pendingRequestId:'REQ1',pendingDeviceId:'NEW',pendingStatus:'PENDING'};c.proof=true;c.operations=[];vm.runInContext(`lookup=async()=>license;verifyEnvelope=async()=>({kind:'bind',licenseId:'L',deviceType:'DESKTOP',requestId:'REQ1'});verifyDeviceSignature=async()=>proof;deviceIdFromPublicKey=async()=> 'NEW';appsCall=async(_e,op)=>{operations.push(op);return receipt};signEnvelope=async()=> 'SESSION';randomId=()=> 'SES1';`,c);return c}
const body={requestId:'REQ1',challenge:'C',publicKeySpki:'KEY',signatureBase64:'SIG'};
test('failed pending write is not reported as waiting for approval',async()=>{const c=harness();c.receipt={valid:false,code:'SERVER_ERROR'};const r=await c.bindDevice(body,{});assert.equal(r.code,'SERVER_ERROR');assert.notEqual(r.code,'DEVICE_APPROVAL_REQUIRED')});
test('missing pending receipt fields fail closed',async()=>{const c=harness();c.receipt={valid:true};assert.equal((await c.bindDevice(body,{})).code,'PENDING_SAVE_UNCONFIRMED')});
test('confirmed pending receipt enters approval flow',async()=>{const c=harness();assert.equal((await c.bindDevice(body,{})).code,'DEVICE_APPROVAL_REQUIRED')});
test('invalid signature cannot request or bind a device',async()=>{const c=harness();c.proof=false;assert.equal((await c.bindDevice(body,{})).code,'DEVICE_SIGNATURE_INVALID');assert.equal(c.operations.length,0)});
test('wrong challenge cannot mutate a binding',async()=>{const c=harness();assert.equal((await c.bindDevice({...body,requestId:'WRONG'},{})).code,'DEVICE_CHALLENGE_INVALID');assert.equal(c.operations.length,0)});
test('unconfirmed new session cannot be reported as bound',async()=>{const c=harness();c.license.activeDeviceId='NEW';c.license.activePublicKey='KEY';c.receipt={valid:true};assert.equal((await c.bindDevice(body,{})).code,'DEVICE_BIND_UNCONFIRMED')});
test('confirmed same-device binding produces session',async()=>{const c=harness();c.license.activeDeviceId='NEW';c.license.activePublicKey='KEY';c.receipt={valid:true,activeDeviceId:'NEW',activePublicKey:'KEY',activeSessionId:'SES1'};const r=await c.bindDevice(body,{});assert.equal(r.bound,true);assert.equal(r.sessionToken,'SESSION')});
test('expiry lookup retains request identity and performs no destructive write',async()=>{const c=harness();c.license.pendingRequestedAt='2020-01-01T00:00:00Z';c.license.pendingRequestId='REQ1';const r=await c.licenseCheck({},{});assert.equal(r.pendingStatus,'EXPIRED');assert.equal(r.pendingRequestId,'REQ1');assert.equal(c.operations.length,0)});
