const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
for(const file of [require('path').join(process.env.TF_REV419_ROOT||'.',process.env.TF_RISK_SOURCE||'assets/4b4d6b8dc315a95c.js')]){
 const s=fs.readFileSync(file,'utf8'),start=s.indexOf('function tf_analystRiskSettings()'),end=s.indexOf('function tf_',s.indexOf('});return result;',start));const data=new Map();const ctx={localStorage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)},currentBalance:5000,getDollarPerPipForAnalyst:(_,p)=>p==='EURUSD'?100:1,getEffectiveSlForAnalyst:()=>({pips:100}),computeSlStatsFromHistory:()=>({}),getRiskPercentForAnalyst:()=>1,computeLot:()=>1,roundLotToTwoDecimals:x=>x};vm.createContext(ctx);vm.runInContext(s.slice(start,end),ctx);
 const norm=x=>x.toLowerCase(),month=t=>new Date(t).toISOString().slice(0,7),src=Array.from({length:6},(_,i)=>({analyst:'a',pair:'XAUUSD',pips:100,sortKey:Date.UTC(2026,i+3,2)}));const check=(loss,pair='XAUUSD')=>ctx.tf_monthlyPnlRisk(src.concat({analyst:'a',pair,pips:-loss,sortKey:Date.UTC(2026,9,2)}),'2026-10',norm,x=>x,r=>r.sortKey,month).get('a');
 assert.equal(check(10,'EURUSD').severity,0,'large dollars cannot override small pips loss');for(const [loss,status] of [[75,0],[75.01,1],[120,1],[120.01,2]])assert.equal(check(loss).severity,status);
 const mixed=src.map((r,i)=>({...r,pips:[-3306.4,2431.4,5422.6,1390.5,2539.2,-233.4][i]}));const actual=ctx.tf_monthlyPnlRisk(mixed.concat({analyst:'a',pair:'XAUUSD',pips:-2066.3,sortKey:Date.UTC(2026,9,2)}),'2026-10',norm,x=>x,r=>r.sortKey,month).get('a');assert.ok(Math.abs(actual.avgPips-2945.925)<1e-8);assert.equal(actual.severity,0);assert.equal(actual.profitMonths,4);
 data.clear();data.set('tfAnalystRiskAdjustment',JSON.stringify({warning:75,critical:100}));assert.equal(ctx.tf_analystRiskSettings().critical,120);data.set('tfAnalystRiskAdjustment',JSON.stringify({warning:80,critical:100}));assert.equal(ctx.tf_analystRiskSettings().critical,100);console.log('PASS pips-only thresholds and migration:',file);
}

