const fs=require('fs'),assert=require('assert/strict'),path=require('path'),{chromium}=require('playwright');
const root=process.env.TF_REV419_ROOT||'outputs/TF_Extension_PC_MAC_REV455_MULTI_LINK',C=require(path.resolve(root,'multi-scanner/core.js'));
const row=(n,i,symbol='XAUUSD')=>({signal_id:String(i),symbol,result:n+' Pips',closed_at_wib:'06-10-2026'});
assert.equal(C.fixed([-150,-150.20,-152.42,-148,-155,-145,-160].map((n,i)=>row(n,i)),'XAUUSD',6,'2026-01-01','2026-10-06')[0].count,6);
assert.equal(C.fixed([-150,-140,-130,-120].map((n,i)=>row(n,i)),'XAUUSD',3,'2026-01-01','2026-10-06').length,0);
assert.equal(C.fixed([row(-150,1),row(-150,1),row(-150,2,'EURUSD'),row(150,3)],'XAUUSD',2,'2026-01-01','2026-10-06').length,0);
(async()=>{const b=await chromium.launch({headless:true,channel:process.env.CI?undefined:'chrome'});try{const p=await b.newPage();await p.setContent(`<a href="#tab_summary">Summary</a><div id="global-filter"><div class="box-header">Filter</div><button id="all">All</button><div id="symbol"><button class="perSymbol active" id="symbol-EURUSD">EURUSD</button><button class="perSymbol" id="symbol-XAUUSD">XAUUSD</button></div><button id="apply">Submit</button></div><div id="tab_summary">2x (-100) Consecutive Loss</div>`);await p.evaluate(()=>{window.calls=[];document.querySelector('#all').onclick=()=>calls.push('time');document.querySelectorAll('.perSymbol').forEach(e=>e.onclick=()=>{calls.push(e.id);e.classList.toggle('active')});document.querySelector('#apply').onclick=()=>{calls.push('submit');if(document.querySelectorAll('.perSymbol.active').length!==1||!document.querySelector('#symbol-XAUUSD.active'))throw Error('Wrong pair at Submit')};});await p.addScriptTag({path:root+'/multi-scanner/collector.js'});const data=await p.evaluate(()=>tfScanDOM('summary',{pair:'XAUUSD'}));assert.match(data.summary,/2x/);assert.deepEqual(await p.evaluate(()=>calls),['time','symbol-EURUSD','symbol-XAUUSD','submit']);const missing=await p.evaluate(()=>tfScanDOM('summary',{pair:'GBPJPY'}));assert.equal(missing.unavailable,true);
await p.evaluate(()=>document.querySelector('#tab_summary').innerText='Loss/Settled\t0/4\n-\nConsecutive Loss');const zero=await p.evaluate(()=>tfScanDOM('summary',{pair:'XAUUSD'}));assert.equal(C.summary(zero.summary),0);assert.throws(()=>C.summary('Loss/Settled\t0/0\n-\nConsecutive Loss'));assert.equal(C.summary('Loss/Settled\t2/4\n-\nConsecutive Loss'),0);
console.log('PASS: Summary ALL → Symbol XAUUSD → Submit; prior pair cleared; unavailable pair reported; ±5 inclusive boundaries, no chain grouping, deduplication and other pairs excluded.');}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
