(async()=>{
  if(window.tfIntegrityReady&&!(await window.tfIntegrityReady))return;
  document.body.innerHTML=`<div class="dashboard"><header><img src="../icon32.png" alt="TF"><div><h1>TF Multi-Link Dashboard</h1><small>Scrape Multi-Link Analis · REV491</small></div></header><main><h1 class="print-title">TF Multi-Link Dashboard — Hasil scan</h1><div class="stats" id="stats"></div><div class="actions"><button id="submit">Submit</button><button id="pause" class="secondary" disabled>Pause</button><button id="xlsx" class="secondary">Export Excel</button><button id="pdf" class="secondary">Export PDF</button><button id="txt" class="secondary">Export TXT</button><button id="evidence" class="secondary">Export JSON</button></div><div class="progress-card"><p id="overall-label" class="notice">Jumlah card belum dihitung.</p><div id="card-progress" hidden><div class="progress-label"><span id="card-label">Card analis</span><span id="card-percent">0%</span></div><div class="progress-track"><div class="progress-fill" id="card-fill"></div></div></div><p id="card-stage" class="notice">Belum berjalan.</p></div><p class="notice" id="progress">Belum ada scan.</p><section><h2 class="success-title">✓ Success</h2><div class="table-wrap result-scroll"><table><thead id="result-head"></thead><tbody id="results"></tbody></table></div></section><section class="skip-section"><h2 class="skip-title">✕ Skip</h2><div class="table-wrap result-scroll"><table id="skip-table"><colgroup><col id="skip-link-col"><col id="skip-analyst-col"><col></colgroup><thead><tr><th>Link</th><th id="skip-name-sort" tabindex="0" role="button">Nama Analis ▲▼</th><th>Reason</th></tr></thead><tbody id="skipped-results"></tbody></table></div></section><section class="filter-summary"><h2>Filter yang dipakai saat scan</h2><div class="filter-summary-grid" id="filter-summary"></div></section><section class="audit"><h2>Catatan pemeriksaan</h2><pre id="filter-info" hidden></pre><div class="logs" id="logs"></div></section></main></div>`;
  const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let skipDirection='asc',sortedSkipped=[],job=null,lastResults='',showFixed=true,displayFilters=TFCore.defaults,sortKey='status',sortDirection='desc',sortedResults=[],startLockedUntil=0;const engine=new TFEngine(render);
  function render(j){job=j;paintSkipped(j);paintFilterSummary(j?.filters);if(!j){lastResults='';sortedResults=[];sortKey='status';sortDirection='desc';$('#stats').innerHTML=[['Total card',0],['Diperiksa',0],['Lolos',0],['Skip',0]].map(([label,n])=>`<div class="stat"><small>${label}</small><b>${n}</b></div>`).join('');$('#submit').disabled=false;$('#submit').textContent='Submit';$('#submit').classList.remove('stop');$('#pause').textContent='Pause';$('#pause').disabled=true;TFMultiProgress.paint(null);$('#progress').textContent='Belum ada scan.';$('#filter-info').textContent='';$('#logs').innerHTML='';paintTable({results:[],evidence:[],filters:displayFilters});return;}$('#stats').innerHTML=[['Total card',j.isPreview?'—':j.inventoryComplete?(j.inventoryCount??j.inventory.length):'Memuat…'],['Diperiksa',j.isPreview?'—':j.cursor],['Lolos',j.isPreview?'—':j.results.length],['Skip',j.isPreview?'—':j.skipped.length]].map(([label,n])=>`<div class="stat"><small>${label}</small><b>${n}</b></div>`).join('');TFMultiProgress.paint(j);const active=['running','paused','error'].includes(j.status);$('#submit').disabled=Date.now()<startLockedUntil;$('#submit').textContent=j.status==='running'?'Stop':active?'Batalkan':'Submit';$('#submit').classList.toggle('stop',j.status==='running');$('#pause').textContent=j.status==='running'?'Pause':'Resume';$('#pause').disabled=!active&&!(j.status==='stopped'&&(!j.inventoryComplete||j.cursor<(j.inventoryCount??j.inventory.length)));const label={running:'Sedang scan',paused:'Dijeda',stopped:'Dihentikan',error:'Error',complete:'Selesai'}[j.status];$('#progress').textContent=`${j.isPreview?'Pratinjau tampilan — bukan hasil scan terbaru':label} · ${j.filters.pair} · ${j.ranges[0].start} s/d ${j.asOf}${j.error?'\n'+j.error:''}`;paintTable(j);$('#filter-info').textContent=JSON.stringify(j.filters,null,2);$('#logs').innerHTML=j.logs.map(s=>`<p>${esc(s)}</p>`).join('');}
  function limitResultRows(){for(const wrap of document.querySelectorAll('.result-scroll')){const table=wrap.querySelector('table'),rows=[...table.tBodies[0].rows];if(rows.length>5){const header=table.tHead.getBoundingClientRect().height,height=header+rows.slice(0,5).reduce((sum,row)=>sum+row.getBoundingClientRect().height,0);wrap.style.maxHeight=Math.ceil(height+Math.max(0,wrap.offsetHeight-wrap.clientHeight))+'px';}else wrap.style.maxHeight='none';}}
  function syncSkipWidths(){limitResultRows();const cells=$('#result-head')?.querySelectorAll('th');if(!cells||cells.length<2)return;const link=cells[0].getBoundingClientRect().width,name=cells[1].getBoundingClientRect().width;if(!link||!name)return;document.documentElement.style.setProperty('--tf-link-width',link+'px');$('#skip-link-col').style.width=link+'px';$('#skip-analyst-col').style.width=name+'px';$('#skip-table').style.minWidth=(link+name+180)+'px';}
  const columnObserver=new ResizeObserver(()=>requestAnimationFrame(syncSkipWidths));columnObserver.observe($('#result-head'));window.addEventListener('resize',()=>requestAnimationFrame(syncSkipWidths));document.fonts?.ready.then(syncSkipWidths);window.addEventListener('beforeprint',syncSkipWidths);window.addEventListener('afterprint',syncSkipWidths);
  function paintSkipped(j){const inventory=new Map((j?.inventory||[]).map(c=>[String(c.id),c]));sortedSkipped=(j?.skipped||[]).map(r=>({...r,reason:r.reason==='Level / Losing Month tidak sesuai'&&inventory.has(String(r.id))?(TFCore.cardRejections(inventory.get(String(r.id)),j.filters).join('; ')||'Alasan scan lama tidak dapat dipastikan; jalankan scan ulang'):r.reason,url:r.url||inventory.get(String(r.id))?.url||j?.evidence?.find(e=>String(e.card?.id)===String(r.id))?.card?.url})).sort((a,b)=>String(a.name).localeCompare(String(b.name),'id',{sensitivity:'base'})*(skipDirection==='asc'?1:-1));$('#skip-name-sort').setAttribute('aria-sort',skipDirection==='asc'?'ascending':'descending');$('#skipped-results').innerHTML=sortedSkipped.map((r,i)=>'<tr><td class="link-cell" data-url="'+esc(r.url)+'">'+(r.url?'<button class="copy-link secondary" data-skip-row="'+i+'">Copy</button>':'—')+'</td><td class="analyst-name-cell">'+(r.url?'<a href="'+esc(r.url)+'" target="_blank" rel="noopener noreferrer">'+esc(r.name)+'</a>':esc(r.name))+'</td><td>'+esc(r.reason||'Alasan tidak tersimpan pada scan lama')+'</td></tr>').join('')||'<tr><td colspan="3">Belum ada analis yang di-skip.</td></tr>';requestAnimationFrame(syncSkipWidths);}
  $('#skip-name-sort').onclick=()=>{skipDirection=skipDirection==='asc'?'desc':'asc';paintSkipped(job);};$('#skip-name-sort').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#skip-name-sort').click();}};
  $('#skipped-results').onclick=async e=>{const b=e.target.closest('[data-skip-row]');if(b){try{await navigator.clipboard.writeText(sortedSkipped[Number(b.dataset.skipRow)].url);b.textContent='Copied';}catch{b.textContent='Copy failed';}}};
  function successExportRows(){return [[...document.querySelectorAll('#result-head th')].map(e=>e.textContent.replace(/[▲▼]/g,'').trim()),...Array.from(document.querySelectorAll('#results tr'),tr=>Array.from(tr.cells,td=>td.classList.contains('link-cell')?td.dataset.url:td.textContent))];}
  function filterExportRows(){return [...document.querySelectorAll('#filter-summary tbody tr')].map(tr=>[...tr.cells].map(c=>c.textContent));}
  function paintFilterSummary(filters){
    const node=$('#filter-summary');if(!filters){node.innerHTML='<p class="notice">Belum ada scan. Filter akan ditampilkan setelah scan dimulai.</p>';return;}
    const f={...TFCore.defaults,...filters},empty=v=>v===undefined||v===null||v==='',num=v=>empty(v)?'Tidak dibatasi':String(v),list=(v,fallback)=>Array.isArray(v)&&v.length?v.join(', '):fallback;
    const bounds=(a,b,unit)=>empty(a)&&empty(b)?'Tidak dibatasi':empty(a)?'Maksimum '+b+unit:empty(b)?'Minimum '+a+unit:a+' – '+b+unit;
    const months=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
    const selectedMonths=[...(f.survivedMonths||[])].sort().map(x=>{const [y,m]=String(x).split('-');return (months[Number(m)-1]||m)+' '+y;}).join(', ');
    const statuses=(f.statuses||[]).map(x=>x==='Basic'?'Basic Channel':x+' Channel');
    const left=[['Main Pair',f.mainPair||'Commodity'],['Pair',(f.pairChoices||[f.pair]).join(', ')],['Level',list(f.levels,'Semua level')],['Status channel',list(statuses,'Semua status')],['Score',bounds(f.scoreMin,f.scoreMax,'')],['Data Sumarry - Portofolio Analis',Number(f.summary)===12?'1 tahun terakhir':f.summary+' bulan terakhir'],['Sort by',({medal:'Medal',score:'Score',probability:'Probability',profit:'Profit'})[f.sort]||f.sort],['Losing Month maksimum',empty(f.losingMax)?'Tidak difilter':f.losingMax+' bulan'],['Losing Month yang diterima',(f.losingAllowed||[]).length===1?'0 – '+f.losingAllowed[0]+' bulan (maksimum)':list(f.losingAllowed,'Tidak difilter')+' bulan (salah satu)'],['Probability',bounds(f.probabilityMin,f.probabilityMax,'%')],['Average TP',bounds(f.tpMin,f.tpMax,' pips')],['Risk : Reward',empty(f.risk)&&empty(f.reward)?'Tidak dibatasi':num(f.risk)+' : '+num(f.reward)],['Avg. Monthly Profit',bounds(f.profitMin,f.profitMax,' pips')],['Max. Loss',empty(f.maxLoss)?'Tidak dibatasi':f.maxLoss+'%']];
    const right=[['Medal',f.medalOn?'ON · '+bounds(f.medalMin,f.medalMax,''):'OFF · dilewati'],['Minimum Portofolio',f.minimumPortfolioOn?'ON · minimum '+f.minimumPortfolioMonths+' bulan':'OFF · dilewati'],['Survived Month',f.survivedOn?(f.survivedMonths.length?'ON · wajib profit > 0 pips setiap bulan':'ON · kosong, pemeriksaan dilewati'):'OFF · dilewati'],['Bulan yang dipilih',f.survivedOn?(selectedMonths||'Belum dipilih'):'Tidak digunakan (OFF)'],['Consecutive Loss maksimum',f.maxConsecutiveOn!==false?'ON · '+f.maxConsecutive+'x':'OFF · dilewati'],['Filter SL Fixed',f.requireFixed?'ON · toleransi ±5 pips · periksa History Signal':'OFF · History Signal dilewati'],['History Signal',f.requireFixed?f.historyMonths+' bulan terakhir (menyesuaikan data tersedia)':'Tidak digunakan (OFF)'],['SL pips yang sama · minimum',f.requireFixed?f.minRepeats+' kejadian':'Tidak digunakan (OFF)'],...TFCore.scoreFields.map(x=>[x.label+' · skor yang diterima',Array.isArray(f[x.key])&&f[x.key].length?f[x.key].map(n=>n+'/4').join(', '):'Tidak difilter'])];
    node.innerHTML=[left,right].map((rows,i)=>'<div class="filter-summary-table"><table aria-label="Ringkasan filter '+(i?'kanan':'kiri')+'"><thead><tr><th>Filter</th><th>Nilai</th></tr></thead><tbody>'+rows.map(([k,v])=>'<tr><td>'+esc(k)+'</td><td>'+esc(v)+'</td></tr>').join('')+'</tbody></table></div>').join('');
  }
  function paintTable(j){
    const specs=TFCore.scoreFields.filter(spec=>(displayFilters[spec.key]||[]).length);
    const columns=[{key:'url',label:'Link',sort:false},{key:'name',label:'Nama Analis'},{key:'monthsSince',label:'Months Since'},{key:'pair',label:'Pair'},{key:'sl',label:'SL Fixed Pips'},...(showFixed?[{key:'repeat',label:'SL Fixed pips<br>Count ('+esc(j.filters.historyMonths||6)+' Mth)'}]:[]),{key:'consecutive',label:'Cons. Loss'},...(specs.some(s=>s.key==='profitFactorAllowed')?[{key:'profitFactor',label:'Profit Factor'}]:[]),...specs.filter(s=>s.key!=='profitFactorAllowed').map(s=>({key:s.field,label:s.label+'<br>Skor',metric:true})),{key:'losing',label:'Losing Month'},{key:'level',label:'Level'},{key:'medal',label:'Medal'},{key:'status',label:'Centang'}];
    const signature=JSON.stringify([j.id,j.results.length,j.results.at(-1)?.url,specs.map(s=>s.key),showFixed,sortKey,sortDirection]);if(signature===lastResults)return;lastResults=signature;
    const scoreEvidence=new Map((j.evidence||[]).map(e=>[e.card?.url,e.profile?.score]));sortedResults=TFCore.sortRows(j.results.map(r=>{const raw=scoreEvidence.get(r.url);const months=r.monthsSince??(j.evidence||[]).find(e=>e.card?.url===r.url)?.portfolio?.months;return {...(raw?TFCore.scoreDetails(raw):{}),...r,monthsSince:months};}),sortKey,sortDirection);
    $('#result-head').innerHTML='<tr>'+columns.map(c=>`<th ${c.sort===false?'':`data-sort="${c.key}" tabindex="0" aria-sort="${sortKey===c.key?(sortDirection==='desc'?'descending':'ascending'):'none'}" style="cursor:pointer"`}>${c.label}${c.sort===false?'':` <span aria-hidden="true" style="color:${sortKey===c.key?'#38bdf8':'#94a3b8'}"><span style="opacity:${sortKey===c.key&&sortDirection==='asc'?1:.35}">▲</span><span style="opacity:${sortKey!==c.key||sortDirection==='desc'?1:.35}">▼</span></span>`}</th>`).join('')+'</tr>';
    $('#results').innerHTML=sortedResults.map((r,i)=>'<tr>'+columns.map(c=>{if(c.key==='url')return `<td class="link-cell" data-url="${esc(r.url)}"><button class="copy-link secondary" data-row="${i}">Copy</button></td>`;if(c.key==='name')return `<td class="analyst-name-cell"><a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.name)}</a></td>`;if(c.key==='status')return `<td class="status ${esc(r.status)}">${r.status==='Basic'?'Basic Channel':'✓ '+esc(r.status)}</td>`;const value=c.key==='sl'&&r.sl==null?'Filter OFF':c.key==='repeat'&&r.slFixedChecked===false?'—':c.metric?(r[c.key]===undefined?'—':r[c.key]+'/4'):r[c.key]??'—';return `<td>${esc(value)}</td>`;}).join('')+'</tr>').join('');for(const cell of $('#result-head').querySelectorAll('th:nth-child(-n+2)'))columnObserver.observe(cell);syncSkipWidths();
  }
  function changeSort(header){if(!header?.dataset.sort)return;const key=header.dataset.sort;sortDirection=sortKey===key?(sortDirection==='desc'?'asc':'desc'):'desc';sortKey=key;if(job)paintTable(job);}
  $('#result-head').onclick=e=>changeSort(e.target.closest('th[data-sort]'));
  $('#result-head').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();changeSort(e.target.closest('th[data-sort]'));}};
  function showError(e){$('#progress').textContent=e.message;}
  async function control(action){const response=await chrome.runtime.sendMessage({type:'TF_MULTI_CONTROL',source:'dashboard-'+action+'-button',action,jobId:job?.id});if(!response?.ok)throw Error(response?.error||'Kontrol tidak merespons.');}
  $('#submit').onclick=async event=>{if(event.detail>1||Date.now()<startLockedUntil)return;startLockedUntil=Date.now()+1500;$('#submit').disabled=true;setTimeout(()=>{if(job)render(job);else $('#submit').disabled=false;},1550);try{if(job&&['running','paused','error'].includes(job.status))return await control('stop');const s=await chrome.storage.local.get('tfMultiFiltersV419');await engine.start(s.tfMultiFiltersV419||TFCore.defaults);}catch(e){showError(e);}};
  $('#pause').onclick=()=>control(job?.status==='running'?'pause':'resume').catch(showError);
  $('#results').onclick=async event=>{const button=event.target.closest('button[data-row]');if(!button)return;try{await navigator.clipboard.writeText(sortedResults[Number(button.dataset.row)].url);button.textContent='Copied';clearTimeout(button.tfCopyTimer);button.tfCopyTimer=setTimeout(()=>{button.textContent='Copy';},2000);}catch{button.textContent='Copy failed';setTimeout(()=>button.textContent='Copy',2000);}};
  const exportAction=fn=>async()=>{try{if(!job||(job.results.length===0&&job.skipped.length===0))throw Error('Belum ada hasil pemeriksaan untuk diekspor.');await fn(job);}catch(e){showError(e);}};
  $('#xlsx').onclick=exportAction(j=>TFExport.download(TFExport.xlsx(sortedResults,sortedSkipped,filterExportRows(),successExportRows()),'tf-multi-link-hasil.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'));
  $('#pdf').onclick=exportAction(()=>window.print());
  $('#txt').onclick=exportAction(j=>TFExport.download(TFExport.txt(sortedResults,sortedSkipped,filterExportRows(),successExportRows()),'tf-multi-link-hasil.txt','text/plain;charset=utf-8'));
  $('#evidence').onclick=async()=>{try{if(job){const {exportParts}=await import('../assets/tf-multi-evidence-export.js');TFExport.download(new Blob(await exportParts(job),{type:'application/json'}),'tf-multi-link-bukti.json','application/json');}}catch(e){showError(e);}};
  const hasChrome=typeof chrome!=='undefined'&&!!chrome.storage;
  if(!hasChrome){$('#submit').disabled=true;$('#progress').textContent='Pratinjau tampilan — runner aktif setelah extension dipasang.';if(globalThis.TFMultiPreviewJob)render(globalThis.TFMultiPreviewJob);return;}
  chrome.storage.onChanged.addListener((c,area)=>{if(area!=='local')return;if(c.tfMultiFiltersV419?.newValue){displayFilters={...TFCore.defaults,...c.tfMultiFiltersV419.newValue};showFixed=displayFilters.requireFixed!==false;if(job)render(job);}if(Object.prototype.hasOwnProperty.call(c,'tfMultiJobV419'))render(c.tfMultiJobV419.newValue?{...c.tfMultiJobV419.newValue,inventory:c.tfMultiJobV419.newValue.inventory?.length?c.tfMultiJobV419.newValue.inventory:(job?.id===c.tfMultiJobV419.newValue.id?job.inventory:[])}:null);if(c.tfMultiProgressV457?.newValue&&c.tfMultiProgressV457.newValue.jobId===job?.id){Object.assign(job,c.tfMultiProgressV457.newValue);render(job);}const cmd=c.tfMultiCommandV419?.newValue;if(cmd&&cmd.jobId===job?.id){if(cmd.action==='pause'||cmd.action==='stop'){engine.interrupt(cmd.action==='stop'?'stopped':'paused',cmd);}else if(cmd.action==='resume')engine.resume(job).catch(showError);}if(c.tfMultiPendingStartV419?.newValue)startPending();});
  async function startPending(){if(engine.running)return;const s=await chrome.storage.local.get(['tfMultiPendingStartV419','tfMultiFiltersV419']);if(!s.tfMultiPendingStartV419)return;await chrome.storage.local.set({tfMultiPendingStartV419:false});await engine.start(s.tfMultiFiltersV419||TFCore.defaults).catch(showError);}
  const s=await chrome.storage.local.get(['tfMultiJobV419','tfMultiCommandV419','tfMultiFiltersV419']);displayFilters={...TFCore.defaults,...(s.tfMultiFiltersV419||s.tfMultiJobV419?.filters||{})};showFixed=displayFilters.requireFixed!==false;if(s.tfMultiJobV419){job=s.tfMultiJobV419;if(job.inventoryKey){const savedInventory=await chrome.storage.local.get(job.inventoryKey);job.inventory=savedInventory[job.inventoryKey]||job.inventory;}render(job);if(job.status==='running'){engine.resume(job).catch(showError);}if(s.tfMultiCommandV419?.action==='resume'&&s.tfMultiCommandV419.jobId===job.id&&['paused','error','stopped'].includes(job.status))engine.resume(job).catch(showError);}else render(null);await startPending();
  window.addEventListener('pagehide',()=>{if(engine.running)chrome.runtime.sendMessage({type:'TF_MULTI_RECOVER',jobId:job.id});});
})();

