globalThis.tfScanDOM=async function(stage,arg={}){
  const q=s=>document.querySelector(s),qa=s=>Array.from(document.querySelectorAll(s)),text=e=>e?.textContent.trim()||'',visible=e=>!!e&&!!e.getClientRects().length,sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const required=s=>{const e=q(s);if(!e)throw Error('Elemen TF tidak ditemukan: '+s);return e;};
  async function until(test,timeout=45000){const end=Date.now()+timeout;while(Date.now()<end){const v=test();if(v)return v;await sleep(200);}throw Error('Halaman belum selesai memuat. Periksa login, jaringan, atau perubahan tampilan TF.');}
  const busy=()=>['#loading-skeleton-new','#modal-load','#modal-load-circle'].some(s=>visible(q(s)));
  async function settle(){await sleep(1200);await until(()=>!busy());const error=q('#notice-err');if(visible(error)&&text(error))throw Error(text(error));}
  const exact=(root,selector,label)=>Array.from(root.querySelectorAll(selector)).find(e=>text(e)===label);
  function setValue(selector,value){const e=required(selector);e.value=value??'';e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));}
  async function selectChips(selector,ids){for(const e of qa(selector+'.active'))e.click();for(const id of ids){const e=required(id);if(e.classList.contains('disabled'))throw Error('Pilihan filter dibatasi TF.');if(!e.classList.contains('active'))e.click();}const selected=qa(selector+'.active').map(e=>e.id);if(selected.length!==ids.length||ids.some(id=>!selected.includes(id.replace(/^#/,''))))throw Error('Pilihan filter tidak cocok.');}
  function cards(){return qa('#channel-content-container .card-symbol[data-id]').map(e=>{const raw=e.innerText,loss=raw.match(/Losing Month\s*(\d+)\s*\/\s*(\d+)/i)||raw.match(/(\d+)\s*\/\s*(\d+)\s*bulan\s*Losing Month/i),level=text(e.querySelector('.channel-name h6 b')),link=e.querySelector('.channel-name a')?.href;if(!loss||!level||!link)throw Error('Card analis belum lengkap: '+e.dataset.id);return {id:e.dataset.id,name:text(e.querySelector('.user_name p')),url:link,level,losing:Number(loss[1]),denominator:Number(loss[2]),raw};});}
  function trades(){return qa('#history-content .container-card[id]').map(e=>{const times={};e.querySelectorAll('.time-card-history p').forEach(p=>{const span=p.querySelector('span');const key=p.textContent.replace(span?.textContent||'','').trim();times[key]=text(span);});const row={signal_id:e.id,symbol:text(e.querySelector('.symbol-card > b')),result:text(e.querySelector('.box-footer')),closed_at_wib:times['Closed at']||null};if(!row.signal_id||!row.symbol||!row.result)throw Error('History Signal tidak lengkap.');if(/Pips/i.test(row.result)&&!row.closed_at_wib)throw Error('Tanggal Closed at tidak terbaca.');return row;});}
  async function tab(name){required(`a[href="#tab_${name}"]`).click();await settle();}
  async function dates(start,end){required('#tglbuat').click();await sleep(100);const picker=qa('.daterangepicker').find(visible);if(!picker)throw Error('Kalender tidak terbuka.');const custom=exact(picker,'.ranges li','Custom Range');if(custom)custom.click();const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];async function pick(side,iso){const [y,m,d]=iso.split('-').map(Number),target=y*12+m-1;while(true){const cal=picker.querySelector('.calendar.'+side),match=text(cal?.querySelector('.month')).match(/([A-Za-z]+)\s+(\d{4})/);if(!match)throw Error('Kalender TF berubah.');const i=months.indexOf(match[1].slice(0,3));if(i<0)throw Error('Nama bulan tidak terbaca.');const current=Number(match[2])*12+i;if(current===target){const cell=Array.from(cal.querySelectorAll('td.available:not(.off)')).find(e=>text(e)===String(d));if(!cell)throw Error('Tanggal tidak tersedia '+iso);cell.click();await sleep(50);return;}const arrow=cal.querySelector(current>target?'.prev.available':'.next.available');if(!arrow)throw Error('Navigasi kalender tidak tersedia.');arrow.click();await sleep(40);}}
    await pick('left',start);await pick('right',end);const parse=v=>{const m=v.match(/(\d{2})\/(\d{2})\/(\d{4})/);return m?`${m[3]}-${m[1]}-${m[2]}`:null;};if(parse(picker.querySelector('[name="daterangepicker_start"]').value)!==start||parse(picker.querySelector('[name="daterangepicker_end"]').value)!==end)throw Error('Rentang tanggal tidak cocok.');picker.querySelector('.applyBtn').click();await sleep(100);
  }
  if(stage==='inventoryStart'){
    await until(()=>q('#channel-content-container'));await settle();const channelButton='button[onclick="openFilterModal(\'channel\')"]';if(!visible(q(channelButton))){required('a[href="#Channel"]').click();await settle();}await until(()=>visible(q(channelButton)));required(channelButton).click();await until(()=>visible(q('#levelSymbol')));
    await selectChips('#levelSymbol .levelSymbolItem',arg.levels.map(v=>'#levelSymbol-'+v));await selectChips('.rankItem',arg.statuses.map(v=>'#rank-'+({Priority:10,Prospect:5,Basic:0}[v])));
    const fields={scoreMin:'#minTotalScore',scoreMax:'#maxTotalScore',losingMax:'#losing',probabilityMin:'#probabilityMin',probabilityMax:'#probabilityMax',tpMin:'#avgMonthlyMin',tpMax:'#avgMonthlyMax',risk:'#rrLeft',reward:'#rrRight',profitMin:'#minPips',profitMax:'#avgProfitMax',maxLoss:'#maxPips'};
    for(const [key,selector]of Object.entries(fields))setValue(selector,arg[key]);required('#find-filter').click();await settle();setValue('#dataSummaryChannel',String(arg.summary));await settle();setValue('#sortBychannel',arg.sort);await settle();return {rows:cards()};
  }
  if(stage==='inventoryMore'){
    await settle();let more=q('button[onclick="loadMoreChannel()"]');if(!visible(more)){await sleep(2000);await settle();more=q('button[onclick="loadMoreChannel()"]');if(!visible(more))return {rows:cards(),done:true,endEvidence:'load_more_absent_after_settle'};}
    if(more.disabled)throw Error('Load More tidak aktif, inventaris belum selesai.');const before=cards().length;more.click();await settle();await until(()=>cards().length>before||(!busy()&&!visible(q('button[onclick="loadMoreChannel()"]'))));await sleep(1000);await settle();const rows=cards();if(rows.length===before&&visible(q('button[onclick="loadMoreChannel()"]')))throw Error('Load More tidak menambah analis.');return {rows,done:!visible(q('button[onclick="loadMoreChannel()"]')),endEvidence:!visible(q('button[onclick="loadMoreChannel()"]'))?'load_more_absent_after_settle':null};
  }
  await until(()=>q('a[href="#tab_summary"]'));
  if(stage==='profile'){
    await tab('summary');const root=required('#global-filter');const all=exact(root,'button','All');if(!visible(all)){required('#global-filter .box-header').click();await sleep(100);}if(!all)throw Error('Time range All tidak tersedia.');all.click();const submit=exact(root,'button','Submit');if(!submit)throw Error('Submit Summary tidak tersedia.');submit.click();await settle();const summary=required('#tab_summary').innerText;await tab('scoring');return {summary,score:required('#tab_scoring').innerText,capturedAt:new Date().toISOString()};
  }
  if(stage==='historyStart'){
    await tab('history');if(!visible(q('#apply-filter'))){required('#tab_history .collapsed-box .box-header').click();await sleep(100);}required('#orderByClose').click();if(!required('#orderByClose').checked)throw Error('Urutan Closed at tidak aktif.');const all=required('#symbol2-All');if(!all.classList.contains('active'))all.click();const pair=q('#symbol2-'+arg.pair);if(!pair)return {unavailable:true,pair:arg.pair};pair.click();const selected=qa('#symbol2 .active').map(text);if(selected.length!==1||selected[0]!==arg.pair)throw Error('Pair history tidak cocok.');await dates(arg.start,arg.end);await until(()=>q('#symbol2-'+arg.pair)&&q('#apply-filter'));const button=required('#apply-filter');if(button.disabled)throw Error('Rentang tanggal ditolak TF.');button.click();await settle();let rows;await until(()=>{try{rows=trades();return !busy();}catch{return false;}});return {rows,filter:text(q('#tglbuat .dateLabel')),pair:arg.pair};
  }
  if(stage==='historyMore'){
    await settle();const before=trades().length;for(let retry=0;retry<2;retry++){window.scrollTo(0,Math.max(0,document.documentElement.scrollHeight-innerHeight-350));await sleep(200);window.scrollTo(0,document.documentElement.scrollHeight);const end=Date.now()+6000;while(Date.now()<end){await sleep(250);if(trades().length>before){await settle();return {rows:trades(),done:false};}}await settle();}
    return {rows:trades(),done:true,endEvidence:'two_scroll_retries_no_more_rows_12_seconds'};
  }
  throw Error('Tahap scan tidak dikenal.');
};
