const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');const root=process.env.TF_REV419_ROOT||'outputs/TF_Extension_PC_MAC_REV419_MULTI_LINK',C=require(path.resolve(root,'multi-scanner/core.js'));
for(const dir of ['assets','multi-scanner'])for(const file of fs.readdirSync(root+'/'+dir).filter(n=>n.endsWith('.js')))new vm.Script(fs.readFileSync(root+'/'+dir+'/'+file,'utf8'),{filename:file});
const store={},removed=[],chrome={storage:{local:{set:async data=>Object.assign(store,structuredClone(data)),get:async keys=>Object.fromEntries((Array.isArray(keys)?keys:[keys]).map(k=>[k,structuredClone(store[k])])),remove:async keys=>(Array.isArray(keys)?keys:[keys]).forEach(k=>delete store[k])}},tabs:{remove:async id=>removed.push(id)}};
let locked=false;const navigator={locks:{request:async(n,o,f)=>{if(locked)return f(null);locked=true;try{return await f({});}finally{locked=false;}}}};
const ctx=vm.createContext({TFCore:C,chrome,navigator,crypto:require('node:crypto').webcrypto,AbortController,structuredClone,setTimeout,clearTimeout,setInterval,clearInterval,Date,console});vm.runInContext(fs.readFileSync(root+'/multi-scanner/engine.js','utf8'),ctx);const Engine=ctx.TFEngine;
const profile={summary:'15x (-1)\nConsecutive Loss',score:'Profit Factor\n1.6\nRecovery Factor\n4.11\n2/4\nStatus Channel\nPriority Channel'};
const cards=Array.from({length:501},(_,i)=>({id:String(i),name:'Analyst '+i,url:'https://account.tradersfamily.id/channels/'+i+'/',level:'Master',losing:i<500?0:1,denominator:12}));
function setup(engine,inventory=cards){engine.navigate=async()=>{engine.check();engine.tabId=17;};let batch=0,range;const dom=async(stage,arg)=>{engine.check();if(stage==='inventoryStart')return {rows:inventory.slice(0,36)};if(stage==='inventoryMore'){batch++;return {rows:inventory.slice(0,36*(batch+1)),done:batch*36+36>=inventory.length,endEvidence:'fixture'};}if(stage==='profile')return profile;if(stage==='historyStart'){range=arg;return {rows:[]};}if(stage==='historyMore'){const [y,m,d]=range.start.split('-');return {rows:range.start===engine.job.ranges[0].start?Array.from({length:10},(_,i)=>({signal_id:String(i),symbol:'XAUUSD',result:'-150.0 Pips',closed_at_wib:`${d}-${m}-${y}`})):[],done:true,endEvidence:'fixture'};}throw Error(stage);};engine.dom=dom;return dom;}
(async()=>{
  const e=new Engine(()=>{});setup(e);await e.start(C.defaults);assert.equal(e.job.cursor,501);assert.equal(e.job.results.length,1);assert.equal(e.job.skipped.length,500);assert.equal(e.job.status,'complete');assert.equal(e.job.progress.fraction,1);
  delete store.tfMultiJobV419;const paused=new Engine(()=>{}),original=setup(paused,[cards[500]]);let reached;const entering=new Promise(r=>reached=r);paused.dom=async(stage,arg)=>{if(stage==='historyMore'){reached();return paused.guarded(new Promise(()=>{}));}return original(stage,arg);};const run=paused.start(C.defaults);await entering;await paused.interrupt('paused');await run;assert.equal(paused.job.status,'paused');assert.equal(paused.job.cursor,0);assert.equal(paused.job.results.length,0);paused.dom=setup(paused,[cards[500]]);await paused.resume(paused.job);assert.equal(paused.job.status,'complete');assert.equal(paused.job.results.length,1);assert.equal(paused.job.cursor,1);
  delete store.tfMultiJobV419;const stopped=new Engine(()=>{}),normal=setup(stopped,[cards[500]]);let entered;const waiting=new Promise(r=>entered=r);stopped.dom=async(stage,arg)=>{if(stage==='profile'){entered();return stopped.guarded(new Promise(()=>{}));}return normal(stage,arg);};const stopRun=stopped.start(C.defaults);await waiting;await stopped.interrupt('stopped');await stopRun;assert.equal(stopped.job.status,'stopped');assert.equal(stopped.job.results.length,0);assert.equal(stopped.job.cursor,0);const status=stopped.job.status;await stopped.resume(stopped.job);assert.equal(stopped.job.status,status);assert.ok(removed.length>=3);assert.ok(removed.every(id=>id===17));
  console.log('PASS: JS syntax, 501 cards, per-card progress, immediate cancellation of pending History/Profile, Pause/Resume with no duplicates, stopped scan cannot resume, only owned tab closed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
