(async()=>{
  if(window.tfIntegrityReady&&!(await window.tfIntegrityReady))return;
  document.body.innerHTML=`<div class="dashboard"><header><img src="../icon32.png" alt="TF"><div><h1>TF Multi-Link Dashboard</h1><small>Scrape Multi-Link Analis · REV424</small></div></header><main><h1 class="print-title">TF Multi-Link Dashboard — Hasil scan</h1><div class="stats" id="stats"></div><div class="actions"><button id="submit">Submit</button><button id="pause" class="secondary" disabled>Pause</button><button id="xlsx" class="secondary">Export Excel</button><button id="pdf" class="secondary">Export PDF</button><button id="txt" class="secondary">Export TXT</button><button id="evidence" class="secondary">Bukti JSON</button></div><div class="progress-card"><p id="overall-label" class="notice">Jumlah card belum dihitung.</p><div id="card-progress" hidden><div class="progress-label"><span id="card-label">Card analis</span><span id="card-percent">0%</span></div><div class="progress-track"><div class="progress-fill" id="card-fill"></div></div></div><p id="card-stage" class="notice">Belum berjalan.</p></div><p class="notice" id="progress">Belum ada scan.</p><section><div class="table-wrap"><table><thead><tr><th>Link</th><th>Nama analis</th><th>Pair</th><th>SL fixed Pips</th><th>Consecutive loss</th><th>Profit factor</th><th>Losing Month</th><th>Level</th><th>Centang</th></tr></thead><tbody id="results"></tbody></table></div></section><section class="audit"><h2>Catatan pemeriksaan</h2><details><summary>Filter yang dipakai</summary><pre id="filter-info"></pre></details><div class="logs" id="logs"></div></section></main></div>`;
  const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let job=null,lastResults='';const engine=new TFEngine(render);
  function render(j){job=j;if(!j)return;$('#stats').innerHTML=[['Total card',j.isPreview?'—':j.inventoryComplete?j.inventory.length:'Memuat…'],['Diperiksa',j.isPreview?'—':j.cursor],['Lolos',j.isPreview?'—':j.results.length],['Skip',j.isPreview?'—':j.skipped.length]].map(([label,n])=>`<div class="stat"><small>${label}</small><b>${n}</b></div>`).join('');TFMultiProgress.paint(j);const active=['running','paused','error'].includes(j.status);$('#submit').textContent=active?'Stop':'Submit';$('#submit').classList.toggle('stop',active);$('#pause').textContent=j.status==='running'?'Pause':'Resume';$('#pause').disabled=!active;const label={running:'Sedang scan',paused:'Dijeda',stopped:'Dihentikan',error:'Error',complete:'Selesai'}[j.status];$('#progress').textContent=`${j.isPreview?'Pratinjau tampilan — bukan hasil scan terbaru':label} · ${j.filters.pair} · ${j.ranges[0].start} s/d ${j.asOf}${j.error?'\n'+j.error:''}`;const signature=JSON.stringify(j.results);if(signature!==lastResults){lastResults=signature;$('#results').innerHTML=j.results.map((r,i)=>`<tr><td class="link-cell" data-url="${esc(r.url)}"><button class="copy-link secondary" data-row="${i}">Copy Link</button></td><td>${esc(r.name)}</td><td>${esc(r.pair)}</td><td>${r.sl}</td><td>${r.consecutive}</td><td>${r.profitFactor}</td><td>${esc(r.losing)}</td><td>${esc(r.level)}</td><td class="status ${esc(r.status)}">${r.status==='Basic'?'Basic Channel':'✓ '+esc(r.status)}</td></tr>`).join('');}$('#filter-info').textContent=JSON.stringify(j.filters,null,2);$('#logs').innerHTML=j.logs.map(s=>`<p>${esc(s)}</p>`).join('');}
  function showError(e){$('#progress').textContent=e.message;}
  async function control(action){const response=await chrome.runtime.sendMessage({type:'TF_MULTI_CONTROL',action,jobId:job?.id});if(!response?.ok)throw Error(response?.error||'Kontrol tidak merespons.');}
  $('#submit').onclick=async()=>{try{if(job&&['running','paused','error'].includes(job.status))return await control('stop');const s=await chrome.storage.local.get('tfMultiFiltersV419');await engine.start(s.tfMultiFiltersV419||TFCore.defaults);}catch(e){showError(e);}};
  $('#pause').onclick=()=>control(job?.status==='running'?'pause':'resume').catch(showError);
  $('#results').onclick=async event=>{const button=event.target.closest('button[data-row]');if(!button)return;try{await navigator.clipboard.writeText(job.results[Number(button.dataset.row)].url);button.textContent='Link Copied!';clearTimeout(button.tfCopyTimer);button.tfCopyTimer=setTimeout(()=>{button.textContent='Copy Link';},2000);}catch{button.textContent='Copy failed';setTimeout(()=>button.textContent='Copy Link',2000);}};
  const exportAction=fn=>async()=>{try{if(!job?.results.length)throw Error('Belum ada hasil lolos.');await fn(job.results);}catch(e){showError(e);}};
  $('#xlsx').onclick=exportAction(rows=>TFExport.download(TFExport.xlsx(rows),'tf-multi-link-hasil.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'));
  $('#pdf').onclick=exportAction(()=>window.print());$('#txt').onclick=exportAction(rows=>TFExport.download(rows.map(r=>r.name+' : '+r.url).join('\r\n'),'tf-multi-link-hasil.txt','text/plain;charset=utf-8'));$('#evidence').onclick=()=>{if(job)TFExport.download(JSON.stringify(job,null,2),'tf-multi-link-bukti.json','application/json');};
  const hasChrome=typeof chrome!=='undefined'&&!!chrome.storage;
  if(!hasChrome){$('#submit').disabled=true;$('#progress').textContent='Pratinjau tampilan — runner aktif setelah extension dipasang.';if(globalThis.TFMultiPreviewJob)render(globalThis.TFMultiPreviewJob);return;}
  chrome.storage.onChanged.addListener((c,area)=>{if(area!=='local')return;if(c.tfMultiJobV419?.newValue)render(c.tfMultiJobV419.newValue);const cmd=c.tfMultiCommandV419?.newValue;if(cmd&&cmd.jobId===job?.id){if(cmd.action==='pause'||cmd.action==='stop'){engine.interrupt(cmd.action==='stop'?'stopped':'paused');}else if(cmd.action==='resume'&&!engine.running)engine.resume(job).catch(showError);}if(c.tfMultiPendingStartV419?.newValue)startPending();});
  async function startPending(){if(engine.running)return;const s=await chrome.storage.local.get(['tfMultiPendingStartV419','tfMultiFiltersV419']);if(!s.tfMultiPendingStartV419)return;await chrome.storage.local.set({tfMultiPendingStartV419:false});await engine.start(s.tfMultiFiltersV419||TFCore.defaults).catch(showError);}
  const s=await chrome.storage.local.get(['tfMultiJobV419','tfMultiCommandV419']);if(s.tfMultiJobV419){job=s.tfMultiJobV419;render(job);if(job.status==='running'){await navigator.locks.request('tf-multi-runner-v419',{ifAvailable:true},async lock=>{if(lock){job.status='paused';job.error='Dashboard sebelumnya ditutup. Klik Resume untuk melanjutkan.';await chrome.storage.local.set({tfMultiJobV419:job,tfMultiHeartbeatV419:0});render(job);}});}if(s.tfMultiCommandV419?.action==='resume'&&s.tfMultiCommandV419.jobId===job.id&&['paused','error'].includes(job.status))engine.resume(job).catch(showError);}await startPending();
  window.addEventListener('pagehide',()=>{if(engine.running){engine.interrupt('paused');chrome.runtime.sendMessage({type:'TF_MULTI_CONTROL',action:'pause',jobId:job.id});}});
})();
