globalThis.tfScanDOM=async function(stage,arg={}){
  const q=s=>document.querySelector(s),qa=s=>Array.from(document.querySelectorAll(s)),text=e=>e?.textContent.trim()||'',visible=e=>!!e&&!!e.getClientRects().length,sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const required=s=>{const e=q(s);if(!e)throw Error('Elemen TF tidak ditemukan: '+s);return e;};
  async function until(test){const started=Date.now();while(true){const v=test();if(v)return v;if(Date.now()-started>180000)throw Error('Panel TF belum memberikan data; muat ulang dan coba kembali.');await sleep(200);}throw Error('Halaman belum selesai memuat. Periksa login, jaringan, atau perubahan tampilan TF.');}
  const busy=()=>['#loading-skeleton-new','#modal-load','#modal-load-circle'].some(s=>visible(q(s)));
  async function settle(){await sleep(1200);await until(()=>!busy());const error=q('#notice-err');if(visible(error)&&text(error))throw Error(text(error));}
  const exact=(root,selector,label)=>Array.from(root.querySelectorAll(selector)).find(e=>text(e)===label);
  function setValue(selector,value){const e=required(selector);e.value=value??'';e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));}
  async function selectChips(selector,ids){for(const e of qa(selector+'.active'))e.click();for(const id of ids){const e=required(id);if(e.classList.contains('disabled'))throw Error('Pilihan filter dibatasi TF.');if(!e.classList.contains('active'))e.click();}const selected=qa(selector+'.active').map(e=>e.id);if(selected.length!==ids.length||ids.some(id=>!selected.includes(id.replace(/^#/,''))))throw Error('Pilihan filter tidak cocok.');}
  function cards(){return qa('#channel-content-container .card-symbol[data-id]').map(e=>{const raw=e.innerText,loss=raw.match(/Losing Month\s*(\d+)\s*\/\s*(\d+)/i)||raw.match(/(\d+)\s*\/\s*(\d+)\s*bulan\s*Losing Month/i),level=text(e.querySelector('.channel-name h6 b')),link=e.querySelector('.channel-name a')?.href;if(!loss||!level||!link)throw Error('Card analis belum lengkap: '+e.dataset.id);return {id:e.dataset.id,name:text(e.querySelector('.user_name p')),url:link,level,status:(e.querySelector('.user_name svg path')?.getAttribute('fill')||'').toUpperCase()==='#00B451'?'Priority':e.querySelector('.user_name svg')?'Prospect':'Basic',losing:Number(loss[1]),denominator:Number(loss[2]),raw};});}
  function trades(){return qa('#history-content .container-card[id]').map(e=>{const times={};e.querySelectorAll('.time-card-history p').forEach(p=>{const span=p.querySelector('span');const key=p.textContent.replace(span?.textContent||'','').trim();times[key]=text(span);});const row={signal_id:e.id,symbol:text(e.querySelector('.symbol-card > b')),result:text(e.querySelector('.box-footer')),closed_at_wib:times['Closed at']||null};if(!row.signal_id||!row.symbol||!row.result)throw Error('History Signal tidak lengkap.');if(/Pips/i.test(row.result)&&!row.closed_at_wib)throw Error('Tanggal Closed at tidak terbaca.');return row;});}
  async function tab(name){required(`a[href="#tab_${name}"]`).click();await settle();}
  async function dates(start,end){required('#tglbuat').click();await sleep(100);const picker=qa('.daterangepicker').find(visible);if(!picker)throw Error('Kalender tidak terbuka.');const custom=exact(picker,'.ranges li','Custom Range');if(custom)custom.click();const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];async function pick(side,iso){const [y,m,d]=iso.split('-').map(Number),target=y*12+m-1;while(true){const cal=picker.querySelector('.calendar.'+side),match=text(cal?.querySelector('.month')).match(/([A-Za-z]+)\s+(\d{4})/);if(!match)throw Error('Kalender TF berubah.');const i=months.indexOf(match[1].slice(0,3));if(i<0)throw Error('Nama bulan tidak terbaca.');const current=Number(match[2])*12+i;if(current===target){const cell=Array.from(cal.querySelectorAll('td.available:not(.off)')).find(e=>text(e)===String(d));if(!cell)throw Error('Tanggal tidak tersedia '+iso);cell.dispatchEvent(new MouseEvent('mouseover',{bubbles:true,relatedTarget:picker}));cell.click();await sleep(50);const fresh=picker.querySelector('.calendar.'+side+' td.active:not(.off)');if(fresh)fresh.dispatchEvent(new MouseEvent('mouseout',{bubbles:true,relatedTarget:picker}));await sleep(50);return;}const arrow=cal.querySelector(current>target?'.prev.available':'.next.available');if(!arrow)throw Error('Navigasi kalender tidak tersedia.');arrow.click();await sleep(40);}}
    await pick('left',start);await pick('right',end);const parse=v=>{const m=v.match(/(\d{2})\/(\d{2})\/(\d{4})/);return m?`${m[3]}-${m[1]}-${m[2]}`:null;};if(parse(picker.querySelector('[name="daterangepicker_start"]').value)!==start||parse(picker.querySelector('[name="daterangepicker_end"]').value)!==end)throw Error('Rentang tanggal tidak cocok.');picker.querySelector('.applyBtn').click();await sleep(100);const label=text(q('#tglbuat .dateLabel'));const parts=label.split(' - ');const applied=parts.map(v=>{const date=new Date(v+' UTC');return Number.isNaN(date.valueOf())?null:date.toISOString().slice(0,10);});if(applied[0]!==start||applied[1]!==end)throw Error('Tanggal hasil Apply tidak cocok: '+label);
  }
  if(stage==='inventoryStart'){
    await until(()=>q('#channel-content-container'));await settle();const channelButton='button[onclick="openFilterModal(\'channel\')"]';if(!visible(q(channelButton))){required('a[href="#Channel"]').click();await settle();}await until(()=>visible(q(channelButton)));required(channelButton).click();await until(()=>visible(q('#levelSymbol')));
    await selectChips('#levelSymbol .levelSymbolItem',arg.levels.map(v=>'#levelSymbol-'+v));await selectChips('.rankItem',arg.statuses.map(v=>'#rank-'+({Priority:10,Prospect:5,Basic:0}[v])));
    const fields={scoreMin:'#minTotalScore',scoreMax:'#maxTotalScore',losingMax:'#losing',probabilityMin:'#probabilityMin',probabilityMax:'#probabilityMax',tpMin:'#avgMonthlyMin',tpMax:'#avgMonthlyMax',risk:'#rrLeft',reward:'#rrRight',profitMin:'#minPips',profitMax:'#avgProfitMax',maxLoss:'#maxPips'};
    for(const [key,selector]of Object.entries(fields))setValue(selector,key==='losingMax'&&arg.losingAllowed?.length?Math.max(...arg.losingAllowed.map(Number)):arg[key]);required('#find-filter').click();await settle();setValue('#dataSummaryChannel',String(arg.summary));await settle();setValue('#sortBychannel',arg.sort);await settle();return {rows:cards()};
  }
  if(stage==='inventoryMore'){
    await settle();let more=q('button[onclick="loadMoreChannel()"]');if(!visible(more)){await sleep(2000);await settle();more=q('button[onclick="loadMoreChannel()"]');if(!visible(more))return {rows:cards(),done:true,endEvidence:'load_more_absent_after_settle'};}
    if(more.disabled)throw Error('Load More tidak aktif, inventaris belum selesai.');const before=cards().length;more.click();await settle();await until(()=>cards().length>before||(!busy()&&!visible(q('button[onclick="loadMoreChannel()"]'))));await sleep(1000);await settle();const rows=cards();if(rows.length===before&&visible(q('button[onclick="loadMoreChannel()"]')))throw Error('Load More tidak menambah analis.');return {rows,done:!visible(q('button[onclick="loadMoreChannel()"]')),endEvidence:!visible(q('button[onclick="loadMoreChannel()"]'))?'load_more_absent_after_settle':null};
  }
  await until(()=>q('a[href="#tab_summary"]'));
  if(stage==='portfolio'){
    await settle();const read=()=>{const box=qa('.chnl-rate').find(e=>/Months \(since/.test(text(e)));const value=text(box?.querySelector('.sumWeek'));const medalMatch=text(qa('.sub-jdl-chnl-comp').find(e=>/Medal\s+\d+/i.test(text(e)))).match(/Medal\s+(\d+)/i);return /^\d+$/.test(value)&&Number(value)>0?{months:Number(value),medal:medalMatch?Number(medalMatch[1]):null,label:text(box),capturedAt:new Date().toISOString()}:null;};return await until(read);
  }
  if(stage==='statistics'){
    await tab('statistic');await until(()=>qa('#tab_statistic .detail-signal').length);const detail=qa('#tab_statistic .btn-telusuri').find(visible);if(!detail)throw Error('Statistics View Details belum tersedia.');detail.click();await settle();await until(()=>visible(q('#ppm-detail-show'))&&qa('#group-year-1 .btn-by-year').length);
    const years=qa('#group-year-1 .btn-by-year').map(e=>e.id);const rows=[];const monthNames=['January','February','March','April','May','June','July','August','September','October','November','December'];
    for(const year of years){required('#group-year-1 [id="'+year+'"]').click();await settle();await until(()=>qa('#ppm-detail-show .month-card').some(e=>e.dataset.year===year));for(const e of qa('#ppm-detail-show .month-card')){if(e.dataset.year!==year)continue;const monthIndex=monthNames.indexOf(e.dataset.month);const raw=text(e.querySelector('.accordion-header'));const match=raw.match(/(-?[\d,.]+)\s*Pips/i);if(monthIndex<0||!match)throw Error('Statistics profit bulanan tidak lengkap.');const pips=Number(match[1].replace(/,/g,''));if(!Number.isFinite(pips))throw Error('Statistics pips tidak terbaca.');rows.push({month:year+'-'+String(monthIndex+1).padStart(2,'0'),pips,raw});}}
    const back=qa('#ppm-detail-show *').find(e=>e.children.length===0&&text(e)==='Kembali');if(back)back.click();await settle();return {rows,years,oldest:rows.map(r=>r.month).sort()[0],capturedAt:new Date().toISOString()};
  }
  if(stage==='score'){
    await tab('scoring');await until(()=>{const value=required('#tab_scoring').innerText;return !busy()&&/Profit Factor/i.test(value)&&/Recovery Factor/i.test(value)&&(value.match(/\b[0-4]\s*\/\s*4\b/g)||[]).length>=7;});return {score:required('#tab_scoring').innerText,capturedAt:new Date().toISOString()};
  }
  if(stage==='profile'||stage==='summary'){
    await tab('summary');const root=required('#global-filter');const all=exact(root,'button','All');if(!visible(all)){required('#global-filter .box-header').click();await sleep(100);}if(!all)throw Error('Time range All tidak tersedia.');all.click();await sleep(100);if(arg.pair){const symbolRoot=required('#symbol');const pair=Array.from(symbolRoot.querySelectorAll('.perSymbol')).find(e=>e.id==='symbol-'+arg.pair||text(e)===arg.pair);if(!pair)return {summary:'',unavailable:true,pair:arg.pair};for(const e of Array.from(symbolRoot.querySelectorAll('.perSymbol.active')))if(e!==pair)e.click();if(!pair.classList.contains('active'))pair.click();const selected=Array.from(symbolRoot.querySelectorAll('.perSymbol.active'));if(selected.length!==1||selected[0]!==pair)throw Error('Symbol Summary tidak cocok: '+arg.pair);}const submit=exact(root,'button','Submit');if(!submit)throw Error('Submit Summary tidak tersedia.');submit.click();await settle();
    await until(()=>!busy()&&(/\d+\s*x\s*\([^\n]*\)\s*Consecutive Loss/i.test(required('#tab_summary').innerText)||(/(?:^|\n)\s*[-–—]\s*\n\s*Consecutive Loss/i.test(required('#tab_summary').innerText)&&/Loss\s*\/\s*Settled\s+\d+\s*\/\s*[1-9]\d*/i.test(required('#tab_summary').innerText))));
    const summary=required('#tab_summary').innerText;if(stage==='summary')return {summary,capturedAt:new Date().toISOString()};await tab('scoring');
    await until(()=>{const value=required('#tab_scoring').innerText;return !busy()&&/Profit Factor/i.test(value)&&/Recovery Factor/i.test(value)&&(value.match(/\b[0-4]\s*\/\s*4\b/g)||[]).length>=7;});
    return {summary,score:required('#tab_scoring').innerText,capturedAt:new Date().toISOString()};
  }
  if(stage==='historyStart'){
    await tab('history');if(!visible(q('#apply-filter'))){required('#tab_history .collapsed-box .box-header').click();await sleep(100);}required('#orderByClose').click();if(!required('#orderByClose').checked)throw Error('Urutan Closed at tidak aktif.');await dates(arg.start,arg.end);await until(()=>q('#symbol2-All')&&q('#apply-filter'));const all=required('#symbol2-All');if(!all.classList.contains('active'))all.click();const pair=q('#symbol2-'+arg.pair);if(!pair)return {unavailable:true,pair:arg.pair};pair.click();const selected=qa('#symbol2 .active').map(text);if(selected.length!==1||selected[0]!==arg.pair)throw Error('Pair history tidak cocok.');await until(()=>q('#symbol2-'+arg.pair)&&q('#apply-filter'));const button=required('#apply-filter');if(button.disabled)throw Error('Rentang tanggal ditolak TF.');button.click();await settle();let rows;await until(()=>{try{rows=trades();return !busy();}catch{return false;}});return {rows,filter:text(q('#tglbuat .dateLabel')),pair:arg.pair};
  }
  if(stage==='historyMore'){
    await settle();const before=trades().length;for(let retry=0;retry<2;retry++){window.scrollTo(0,Math.max(0,document.documentElement.scrollHeight-innerHeight-350));await sleep(200);window.scrollTo(0,document.documentElement.scrollHeight);const end=Date.now()+6000;while(Date.now()<end){await sleep(250);if(trades().length>before){await settle();return {rows:trades(),done:false};}}await settle();}
    return {rows:trades(),done:true,endEvidence:'two_scroll_retries_no_more_rows_12_seconds'};
  }
  throw Error('Tahap scan tidak dikenal.');
};
