(function(root){
  const defaults={levels:['Elite','Master'],statuses:['Priority','Prospect'],scoreMin:'',scoreMax:'',losingMax:2,probabilityMin:40,probabilityMax:100,tpMin:'',tpMax:'',risk:'',reward:'',profitMin:500,profitMax:10000,maxLoss:50,summary:12,sort:'medal',losingAllowed:[1,2],maxConsecutive:15,recoveryAllowed:[1,2],levelScoreAllowed:[],statusScoreAllowed:[],subscriberAllowed:[],monthlyLossAllowed:[],profitMonthsAllowed:[],profitFactorAllowed:[1,2],pair:'XAUUSD',minimumPortfolioOn:true,minimumPortfolioMonths:6,survivedOn:false,survivedMonths:[],historyMonths:6,minRepeats:10,fixedRepeatsOn:true,requireFixed:true};
  const iso=d=>d.toISOString().slice(0,10);
  function ranges(end,months=6){const finish=new Date(end+'T00:00:00Z'),start=new Date(finish);start.setUTCDate(1);start.setUTCMonth(start.getUTCMonth()-months);start.setUTCDate(Math.min(finish.getUTCDate(),new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,0)).getUTCDate()));const out=[];let cursor=start;while(cursor<=finish){const last=new Date(cursor);last.setUTCDate(last.getUTCDate()+89);if(last>finish)last.setTime(finish.getTime());out.push({start:iso(cursor),end:iso(last)});cursor=new Date(last);cursor.setUTCDate(cursor.getUTCDate()+1);}return out;}
  function pips(raw){if(!/^\s*-?\d[\d,.]*\s*Pips\s*$/i.test(raw||''))return null;const n=Number(raw.replace(/\s*Pips/i,'').trim().replace(/,/g,''));return Number.isFinite(n)?n:null;}
  function closedDate(raw){const m=(raw||'').match(/(\d{2})-(\d{2})-(\d{4})/);return m?`${m[3]}-${m[2]}-${m[1]}`:null;}
  function fixed(rows,pair,minRepeats,start,end){const seen=new Set(),counts=new Map();for(const r of rows){const id=r.signal_id||r.id;if(!id||seen.has(id))continue;seen.add(id);if((r.symbol||r.pair)!==pair)continue;const date=closedDate(r.closed_at_wib||r.closed);if(!date||date<start||date>end)continue;const n=pips(r.result);if(n!==null&&n<0)counts.set(n,(counts.get(n)||0)+1);}const values=Array.from(counts,([value,exactCount])=>({value,exactCount}));return values.map(r=>({...r,count:values.reduce((n,x)=>n+(Math.abs(x.value-r.value)<=5+1e-9?x.exactCount:0),0),tolerance:5})).filter(r=>r.count>=minRepeats).sort((a,b)=>b.count-a.count||b.exactCount-a.exactCount||a.value-b.value);}
  function summary(text){const m=text.match(/(\d+)x[^\n]*\n\s*Consecutive Loss/i);if(!m)throw Error('Consecutive Loss tidak terbaca.');return Number(m[1]);}
  function score(text){const rf=text.match(/Recovery Factor\s*([\d.,]+)\s*([0-4])\/4/i),pf=text.match(/Profit Factor\s*([\d.,]+)/i),status=text.match(/Status Channel\s*(Priority Channel|Prospect Channel|Basic Channel)/i);if(!rf||!pf||!status)throw Error('Score / Recovery Factor / status tidak lengkap.');const decimal=s=>Number(s.includes('.')?s.replace(/,/g,''):s.replace(',','.'));const recovery=decimal(rf[1]),profitFactor=decimal(pf[1]);if(!Number.isFinite(recovery)||!Number.isFinite(profitFactor))throw Error('Angka Score tidak terbaca.');return {recovery,recoveryScore:Number(rf[2]),profitFactor,status:status[1].replace(' Channel','')};}
  function cardAllowed(c,f){return (!f.levels.length||f.levels.includes(c.level))&&c.denominator===Number(f.summary)&&f.losingAllowed.includes(c.losing);}
  function validate(f){f.fixedRepeatsOn=true;if(f.minimumPortfolioOn===undefined)f.minimumPortfolioOn=true;if(f.minimumPortfolioMonths===undefined)f.minimumPortfolioMonths=6;if(f.survivedOn===undefined)f.survivedOn=false;if(f.survivedMonths===undefined)f.survivedMonths=[];if(typeof f.minimumPortfolioOn!=='boolean'||typeof f.survivedOn!=='boolean'||![3,6,8,10,12].includes(f.minimumPortfolioMonths)||![3,6].includes(f.historyMonths))throw Error('Pilihan bulan tidak valid.');if(!Array.isArray(f.survivedMonths)||f.survivedMonths.some(m=>!monthOptions().includes(m)))throw Error('Survived Month tidak valid.');if(f.survivedOn&&!f.survivedMonths.length)throw Error('Pilih minimal satu Survived Month.');if(f.requireFixed===undefined)f.requireFixed=true;if(typeof f.requireFixed!=='boolean')throw Error('Filter SL Fixed harus ON atau OFF.');if(f.levels.length>2||f.statuses.length>2)throw Error('Seperti TF, pilih maksimal dua level dan dua status.');for(const [a,b] of [['scoreMin','scoreMax'],['probabilityMin','probabilityMax'],['tpMin','tpMax'],['profitMin','profitMax']])if(f[a]!==''&&f[b]!==''&&Number(f[a])>Number(f[b]))throw Error('Nilai minimum harus ≤ maksimum.');if(!f.losingAllowed.length)throw Error('Pilih Losing Month yang diterima.');if(!/^[A-Z0-9]{3,20}$/.test(f.pair))throw Error('Pair tidak valid.');if(f.minRepeats<1||f.historyMonths<1||f.historyMonths>60||f.maxConsecutive<0)throw Error('Batas pemeriksaan tidak valid.');return f;}
  const pairs=["XAUUSD","AUDJPY","CHFJPY","CADJPY","GBPJPY","EURJPY","NZDJPY","USDJPY","GBPUSD","EURUSD","USDCHF","USDCAD","AUDUSD","NZDUSD","EURGBP","EURNZD"];
  const scoreFields=[{key:'levelScoreAllowed',field:'levelScore',label:'Level'},{key:'statusScoreAllowed',field:'statusScore',label:'Status Channel'},{key:'subscriberAllowed',field:'subscriberScore',label:'Subscriber'},{key:'profitFactorAllowed',field:'profitFactorScore',label:'Profit Factor'},{key:'monthlyLossAllowed',field:'monthlyLossScore',label:'Mthly. Loss Ratio'},{key:'profitMonthsAllowed',field:'profitMonthsScore',label:'Profit Month'},{key:'recoveryAllowed',field:'recoveryScore',label:'Recovery Factor'}];
  function scoreDetails(text){const result={};for(const spec of scoreFields){const label=spec.label==='Profit Month'?'Profit Months?':spec.label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const m=text.match(new RegExp(label+'\\s+([^\\n]+)\\s+([0-4])/4','i'));if(m){result[spec.field]=Number(m[2]);result[spec.field+'Value']=m[1].trim();}}return result;}
  function accepted(score,f){for(const spec of scoreFields){const allowed=f[spec.key]||[];if(allowed.length&&!allowed.includes(score[spec.field]))return spec.label+' '+(score[spec.field]===undefined?'tidak terbaca':score[spec.field]+'/4');}return null;}
  function sortRows(rows,key='status',direction='desc'){const levels=['Newbie','Rookie','Pro','Elite','Master','Legend'],statuses=['Basic','Prospect','Priority'];const value=r=>key==='level'?levels.indexOf(r.level):key==='status'?statuses.indexOf(r.status):key==='losing'?Number(String(r.losing).split('/')[0]):r[key];return rows.map((r,i)=>({r,i})).sort((a,b)=>{let x=value(a.r),y=value(b.r);if(x==null||y==null){if(x==null&&y!=null)return 1;if(y==null&&x!=null)return -1;}let c=typeof x==='string'?x.localeCompare(String(y),'en',{sensitivity:'base'}):Number(x)-Number(y);if(c)return direction==='asc'?c:-c;if(key==='status'){c=Number(b.r.profitFactor)-Number(a.r.profitFactor);if(c)return c;}return a.i-b.i;}).map(x=>x.r);}
  function monthOptions(now=new Date()){const out=[];const end=now.getFullYear()*12+now.getMonth();for(let n=2024*12;n<=end;n++)out.push(Math.floor(n/12)+'-'+String(n%12+1).padStart(2,'0'));return out;}
  function survived(rows,selected){const values=new Map(rows.map(r=>[r.month,r.pips]));for(const month of selected){const p=values.get(month);if(!Number.isFinite(p)||p<=0)return 'Survived Month '+month+': '+(Number.isFinite(p)?p+' Pips':'data tidak tersedia');}return null;}
  function availableRanges(end,months,portfolioMonths,oldest){let count=Math.min(months,portfolioMonths);if(!Number.isInteger(count)||count<1)throw Error('Umur portofolio belum tersedia.');const windows=ranges(end,count);const first=oldest?oldest+'-01':null;return windows.map(w=>({...w,start:first&&w.start<first?first:w.start})).filter(w=>w.start<=w.end);}
  const api={monthOptions,survived,availableRanges,scoreFields,scoreDetails,accepted,sortRows,pairs,defaults,ranges,pips,closedDate,fixed,summary,score,cardAllowed,validate};root.TFCore=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
