(function(root){
  const defaults={levels:['Elite','Master'],statuses:['Priority','Prospect'],scoreMin:'',scoreMax:'',losingMax:2,probabilityMin:40,probabilityMax:100,tpMin:'',tpMax:'',risk:'',reward:'',profitMin:500,profitMax:10000,maxLoss:50,summary:12,sort:'medal',losingAllowed:[1,2],maxConsecutive:15,recoveryAllowed:[2,3,4],pair:'XAUUSD',historyMonths:6,minRepeats:10,requireFixed:true};
  const iso=d=>d.toISOString().slice(0,10);
  function ranges(end,months=6){const finish=new Date(end+'T00:00:00Z'),start=new Date(finish);start.setUTCDate(1);start.setUTCMonth(start.getUTCMonth()-months);start.setUTCDate(Math.min(finish.getUTCDate(),new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,0)).getUTCDate()));const out=[];let cursor=start;while(cursor<=finish){const last=new Date(cursor);last.setUTCDate(last.getUTCDate()+89);if(last>finish)last.setTime(finish.getTime());out.push({start:iso(cursor),end:iso(last)});cursor=new Date(last);cursor.setUTCDate(cursor.getUTCDate()+1);}return out;}
  function pips(raw){if(!/^\s*-?\d[\d,.]*\s*Pips\s*$/i.test(raw||''))return null;const n=Number(raw.replace(/\s*Pips/i,'').trim().replace(/,/g,''));return Number.isFinite(n)?n:null;}
  function closedDate(raw){const m=(raw||'').match(/(\d{2})-(\d{2})-(\d{4})/);return m?`${m[3]}-${m[2]}-${m[1]}`:null;}
  function fixed(rows,pair,minRepeats,start,end){const seen=new Set(),counts=new Map();for(const r of rows){const id=r.signal_id||r.id;if(!id||seen.has(id))continue;seen.add(id);if((r.symbol||r.pair)!==pair)continue;const date=closedDate(r.closed_at_wib||r.closed);if(!date||date<start||date>end)continue;const n=pips(r.result);if(n!==null&&n<0)counts.set(n,(counts.get(n)||0)+1);}return Array.from(counts,([value,count])=>({value,count})).filter(r=>r.count>=minRepeats).sort((a,b)=>b.count-a.count||a.value-b.value);}
  function summary(text){const m=text.match(/(\d+)x[^\n]*\n\s*Consecutive Loss/i);if(!m)throw Error('Consecutive Loss tidak terbaca.');return Number(m[1]);}
  function score(text){const rf=text.match(/Recovery Factor\s*([\d.,]+)\s*([0-4])\/4/i),pf=text.match(/Profit Factor\s*([\d.,]+)/i),status=text.match(/Status Channel\s*(Priority Channel|Prospect Channel|Basic Channel)/i);if(!rf||!pf||!status)throw Error('Score / Recovery Factor / status tidak lengkap.');const decimal=s=>Number(s.includes('.')?s.replace(/,/g,''):s.replace(',','.'));const recovery=decimal(rf[1]),profitFactor=decimal(pf[1]);if(!Number.isFinite(recovery)||!Number.isFinite(profitFactor))throw Error('Angka Score tidak terbaca.');return {recovery,recoveryScore:Number(rf[2]),profitFactor,status:status[1].replace(' Channel','')};}
  function cardAllowed(c,f){return (!f.levels.length||f.levels.includes(c.level))&&c.denominator===Number(f.summary)&&f.losingAllowed.includes(c.losing);}
  function validate(f){if(f.requireFixed===undefined)f.requireFixed=true;if(typeof f.requireFixed!=='boolean')throw Error('Filter SL Fixed harus ON atau OFF.');if(f.levels.length>2||f.statuses.length>2)throw Error('Seperti TF, pilih maksimal dua level dan dua status.');for(const [a,b] of [['scoreMin','scoreMax'],['probabilityMin','probabilityMax'],['tpMin','tpMax'],['profitMin','profitMax']])if(f[a]!==''&&f[b]!==''&&Number(f[a])>Number(f[b]))throw Error('Nilai minimum harus ≤ maksimum.');if(!f.losingAllowed.length||!f.recoveryAllowed.length)throw Error('Pilih Losing Month dan Recovery Factor yang diterima.');if(!/^[A-Z0-9]{3,20}$/.test(f.pair))throw Error('Pair tidak valid.');if(f.minRepeats<1||f.historyMonths<1||f.historyMonths>60||f.maxConsecutive<0)throw Error('Batas pemeriksaan tidak valid.');return f;}
  const api={defaults,ranges,pips,closedDate,fixed,summary,score,cardAllowed,validate};root.TFCore=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
