from pathlib import Path
import sys,json,re,hashlib
root=Path(sys.argv[1])
popup="<div id=\"tf-risk-explainer\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"tf-risk-explainer-title\"><div class=\"tf-risk-explainer-card\"><div class=\"tf-risk-explainer-eyebrow\">// ANALYST STATUS</div><h2 id=\"tf-risk-explainer-title\">Status<br>Analis</h2><p>Kenali warna dan ikon sebelum membaca dashboard. Status memakai periode maksimum dari seluruh data Table 3, lalu dibandingkan dengan bulan data paling baru.</p><div class=\"tf-risk-explainer-row tf-risk-green\"><span class=\"tf-risk-explainer-icon\" aria-hidden=\"true\">✓</span><div><strong>Hijau · Centang</strong><span>Nama analis hijau: di bulan terbaru tidak ada maximum consecutive loss maupun maximum drawdown.</span></div></div><div class=\"tf-risk-explainer-row tf-risk-yellow\"><span class=\"tf-risk-explainer-icon\" aria-hidden=\"true\">!</span><div><strong>Kuning · Tanda seru</strong><span>Nama analis kuning: di bulan terbaru ada salah satu, maximum consecutive loss atau maximum drawdown.</span></div></div><div class=\"tf-risk-explainer-row tf-risk-red\"><span class=\"tf-risk-explainer-icon\" aria-hidden=\"true\">×</span><div><strong>Merah · X</strong><span>Nama analis merah: di bulan terbaru ada maximum consecutive loss dan maximum drawdown.</span></div></div><button id=\"tf-risk-explainer-understand\" type=\"button\">Mengerti !</button><div class=\"tf-risk-explainer-footer\">TF ANALYZER <span>TABLE 3 · BULAN TERBARU</span></div></div></div>"
hook="\ndocument.body.classList.add('tf-risk-explainer-open');\ndocument.getElementById('tf-risk-explainer-understand').addEventListener('click',()=>{document.getElementById('tf-risk-explainer')?.remove();document.body.classList.remove('tf-risk-explainer-open');},{once:true});\n"
css="\n/* REV407: Pulse Reactor card with Halo-style cyan/blue/violet title. */\nbody.tf-risk-explainer-open{overflow:hidden!important;}\n#tf-risk-explainer{position:fixed;inset:0;z-index:2147483000;display:flex;align-items:center;justify-content:center;background:rgba(4,10,17,.96);padding:18px;overflow:auto;}\n#tf-risk-explainer .tf-risk-explainer-card{width:100%;max-width:440px;max-height:calc(100dvh - 36px);overflow:auto;padding:28px;border:1px solid rgba(56,189,248,.18);border-radius:18px;background:radial-gradient(ellipse at 20% 25%,rgba(22,77,111,.18),transparent 75%),#090f18;color:#dbeafe;box-sizing:border-box;box-shadow:0 20px 80px rgba(0,0,0,.24);}\n#tf-risk-explainer .tf-risk-explainer-eyebrow{color:#38d1ff;font:10px ui-monospace,SFMono-Regular,Consolas,monospace;letter-spacing:2.4px;margin-bottom:24px;}\n#tf-risk-explainer h2{font-family:system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif;font-size:36px!important;font-weight:800!important;line-height:1!important;letter-spacing:-1px;margin:0 0 22px!important;background:linear-gradient(100deg,#00e5ef 0%,#38a9ff 42%,#9665ff 85%);background-clip:text;-webkit-background-clip:text;color:transparent!important;-webkit-text-fill-color:transparent;}\n#tf-risk-explainer p{font:11px/1.7 ui-monospace,SFMono-Regular,Consolas,monospace;color:#94a3b8;margin:0 0 22px;}\n#tf-risk-explainer .tf-risk-explainer-row{display:flex;align-items:flex-start;gap:12px;margin:16px 0;}\n#tf-risk-explainer .tf-risk-explainer-row>div{flex:1;min-width:0;}\n#tf-risk-explainer .tf-risk-explainer-row strong{display:block;font-size:12px;line-height:1.4;margin:0 0 5px;}\n#tf-risk-explainer .tf-risk-explainer-row span:not(.tf-risk-explainer-icon){display:block;font-size:11px;line-height:1.6;color:#a9bdd0;}\n#tf-risk-explainer .tf-risk-explainer-icon{display:flex;align-items:center;justify-content:center;width:24px;height:24px;flex:0 0 24px;border:1px solid currentColor;border-radius:50%;font:700 14px/1 system-ui;margin-top:1px;}\n#tf-risk-explainer .tf-risk-green{color:#22c55e;}\n#tf-risk-explainer .tf-risk-yellow{color:#facc15;}\n#tf-risk-explainer .tf-risk-red{color:#ef4444;}\n#tf-risk-explainer button{width:100%;min-height:44px;margin-top:14px;border:1px solid rgba(56,189,248,.5);border-radius:7px;background:rgba(56,189,248,.08);color:#55d6ff;font-size:12px;font-weight:600;letter-spacing:.6px;cursor:pointer;}\n#tf-risk-explainer button:hover,#tf-risk-explainer button:focus-visible{background:rgba(56,189,248,.17);outline:2px solid rgba(56,189,248,.2);outline-offset:3px;}\n#tf-risk-explainer .tf-risk-explainer-footer{display:flex;justify-content:space-between;gap:12px;margin-top:22px;padding-top:14px;border-top:1px solid #1b2533;color:#64748b;font:8px/1.4 ui-monospace,SFMono-Regular,Consolas,monospace;letter-spacing:1px;}\n@media(max-width:380px){#tf-risk-explainer .tf-risk-explainer-card{padding:22px;}#tf-risk-explainer h2{font-size:32px!important;}}\n"
f=root/'assets/4b4d6b8dc315a95c.js';s=f.read_text();m=re.match(r'document.body.innerHTML = (".*?");',s,re.S);assert m
body=json.loads(m.group(1));body+=popup;s=s[:m.start()]+ 'document.body.innerHTML = '+json.dumps(body,ensure_ascii=False)+';'+hook+s[m.end():];f.write_text(s)
f=root/'assets/7e95b596e5bf8dff.css';f.write_text(f.read_text()+css)
f=root/'manifest.json';m=json.loads(f.read_text());m.update(version='1.17.20',version_name='REV407');f.write_text(json.dumps(m,indent=2)+'\n')
f=root/'assets/7b6af0cb4001a684.js';s=f.read_text();m=re.search(r'const FILES\s*=\s*(\{.*?\});',s,re.S);d=json.loads(m.group(1));d={p:hashlib.sha256((root/p).read_bytes()).hexdigest() for p in d};f.write_text(s[:m.start(1)]+json.dumps(d,separators=(',',':'))+s[m.end(1):])

